/**
 * Influence Game - House Interviewer
 *
 * The House is the omniscient narrator and production staff of the game.
 * During diary room sessions, The House interviews each player with
 * contextual, personality-driven questions generated via LLM.
 */

import type OpenAI from "openai";
import type { ChatCompletion } from "openai/resources/chat/completions";
import type { LlmToolChoiceMode } from "./llm-client";
import { Phase } from "./types";
import type { MingleIntentSummary, UUID } from "./types";
import type { TokenTracker } from "./token-tracker";
import {
  inferModelCapabilities,
  type ModelReasoningEffort,
  type ModelReasoningPolicy,
  type ModelRequestCapabilities,
  type ProviderProfileId,
} from "./model-catalog";
import type {
  HouseAllianceHypothesis,
  HouseCouncilRoleFact,
  HouseConfidence,
  HouseCoveredWindow,
  HouseGameplaySummaryContext,
  HouseGameplaySummaryResult,
  HousePlayerTrajectory,
  HouseProducerBrief,
  HouseRoundFacts,
  HouseStoryArc,
  HouseStrategyBiblePacket,
  HouseStrategyBibleUpdateContext,
  HouseStrategyBibleUpdateResult,
  HouseVoteCount,
  PrivateDecisionTrace,
  PrivateDecisionTraceContext,
  PrivateDecisionTraceMessage,
  PrivateDecisionTraceToolCall,
  PrivateTraceSink,
  TranscriptEntry,
} from "./game-runner.types";

// ---------------------------------------------------------------------------
// Interview context passed to the House
// ---------------------------------------------------------------------------

export interface DiaryRoomContext {
  /** Which phase just completed */
  precedingPhase: Phase;
  /** Current round number */
  round: number;
  /** The agent being interviewed */
  agentName: string;
  /** All alive players */
  alivePlayers: string[];
  /** Currently active shields on living players */
  activeShieldNames: string[];
  /** Recently eliminated players (if any) */
  eliminatedPlayers: string[];
  /** Most recently eliminated player name */
  lastEliminated: string | null;
  /** Who is currently empowered (if known) */
  empoweredName: string | null;
  /** Council candidates (if in reveal/council context) */
  councilCandidates: [string, string] | null;
  /** Recent public messages for context */
  recentMessages: Array<{ from: string; text: string; phase: Phase }>;
  /** This player's previous diary room Q&A entries */
  previousDiaryEntries?: Array<{ round: number; question: string; answer: string }>;
  /** Messages this specific player sent recently */
  playerMessages?: Array<{ text: string; phase: Phase }>;
  /** Private producer/debug brief generated by the House before the visible question. */
  producerBrief?: HouseProducerBrief | null;
  /** Authoritative facts for the current round from canonical events/projections. */
  roundFacts?: HouseRoundFacts;
  /** This interviewee's role in the latest Council, if a Council happened. */
  councilRole?: HouseCouncilRoleFact | null;
}

export interface HouseMingleAssignmentPlayer {
  id: UUID;
  name: string;
  intent: MingleIntentSummary | null;
}

export interface HouseMingleAssignmentContext {
  round: number;
  roomCount: number;
  players: HouseMingleAssignmentPlayer[];
}

export interface HouseMingleRoomAssignment {
  roomId: number;
  playerIds: UUID[];
}

export interface HouseMingleAssignmentResult {
  rooms: HouseMingleRoomAssignment[];
  rationale?: string;
  thinking?: string;
  reasoningContext?: string;
}

// ---------------------------------------------------------------------------
// Interface
// ---------------------------------------------------------------------------

/** Result from the House deciding whether to ask another question or wrap up. */
export type FollowUpResult =
  | { type: "question"; question: string }
  | { type: "close"; message: string };

export interface IHouseInterviewer {
  /** Assign initial Mingle rooms from all hidden Mingle intents. The phase validator repairs/finalizes output. */
  assignMingleRooms(context: HouseMingleAssignmentContext): Promise<HouseMingleAssignmentResult>;
  /** Update the private House Strategy Bible Packet from the previous packet and current producer evidence. */
  updateStrategyBible(context: HouseStrategyBibleUpdateContext): Promise<HouseStrategyBibleUpdateResult>;
  /** Generate a packet-backed concise House MC summary. */
  generateHouseSummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult>;
  /** Generate a richer packet-backed gameplay catch-up summary for producer validation. */
  generateLongFormGameplaySummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult>;
  /** Generate a private producer brief before asking a diary-room question. */
  generateProducerBrief(context: DiaryRoomContext, packet: HouseStrategyBiblePacket | null): Promise<HouseProducerBrief>;
  /** Generate the first diary room interview question for an agent */
  generateQuestion(context: DiaryRoomContext): Promise<string>;
  /** Decide whether to ask a follow-up or close the session. */
  generateFollowUpOrClose(
    context: DiaryRoomContext,
    conversationSoFar: Array<{ question: string; answer: string }>,
  ): Promise<FollowUpResult>;

  /**
   * Generate a dramatic House MC-style narrative summary of recent gameplay.
   * Used for in-progress simulation traces to make them more engaging.
   */
  generateGameplaySummary(recentTranscript: TranscriptEntry[], round: number, phase: Phase, alivePlayers: string[]): Promise<string>;
}

export interface LLMHouseInterviewerOptions {
  privateTraceSink?: PrivateTraceSink;
  gameId?: UUID;
  ownerEpoch?: string;
  toolChoiceMode?: LlmToolChoiceMode;
  structuredOutputTimeoutMs?: number;
  providerProfileId?: ProviderProfileId;
  modelCapabilities?: ModelRequestCapabilities;
  reasoningPolicy?: ModelReasoningPolicy;
  catalogId?: string;
}

// ---------------------------------------------------------------------------
// LLM-driven House Interviewer
// ---------------------------------------------------------------------------

const HOUSE_PERSONALITY = `You are "The House" — the omniscient narrator and showrunner of "Influence", a social strategy game where AI agents scheme, betray, and eliminate each other.

Your personality:
- You are dramatic, perceptive, and darkly witty — like the best reality TV producers
- You see EVERYTHING: every Mingle-room conversation, every alliance, every betrayal
- You ask questions that provoke genuine strategic reflection and great entertainment
- You sometimes hint at things the player doesn't know you've seen
- You vary your style: sometimes pointed, sometimes sympathetic, sometimes provocatively blunt
- You never reveal secrets outright, but you love to needle players about their contradictions
- You address each player by name and tailor your question to THEIR specific situation

Rules:
- Ask ONE question at a time (can be multi-part)
- Keep it to 1-2 sentences
- EVERY question must reference a SPECIFIC player name, quote, or event from the game state below
- BANNED generic openers: "what's on your mind?", "what's your strategy?", "how are you feeling?", "what do you think about the game?", "what's your read on things?"
- BANNED vague prompts: "tell us about...", "walk us through...", "what happened in..."
- Instead, be SHARP: "You told [name] you'd protect them — was that a lie?", "When [name] said [quote], you flinched — what were you thinking?", "[Name] voted against you last round. Are you going to let that slide?"
- If you have their previous diary answers, call out a specific contradiction or broken promise
- Respond with ONLY the question text, nothing else`;

function extractJsonObject(raw: string): Record<string, unknown> | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  try {
    return JSON.parse(trimmed) as Record<string, unknown>;
  } catch {
    const first = trimmed.indexOf("{");
    const last = trimmed.lastIndexOf("}");
    if (first === -1 || last <= first) return null;
    try {
      return JSON.parse(trimmed.slice(first, last + 1)) as Record<string, unknown>;
    } catch {
      return null;
    }
  }
}

function parseHouseMingleAssignmentRecord(parsed: Record<string, unknown>): HouseMingleAssignmentResult {
  const rawRooms = Array.isArray(parsed.rooms) ? parsed.rooms : [];
  const rooms = rawRooms
    .map((room): HouseMingleRoomAssignment | null => {
      if (!room || typeof room !== "object") return null;
      const roomRecord = room as Record<string, unknown>;
      const roomId = Number(roomRecord.roomId);
      const rawPlayers = Array.isArray(roomRecord.playerIds)
        ? roomRecord.playerIds
        : Array.isArray(roomRecord.players)
          ? roomRecord.players
          : [];
      const playerIds = rawPlayers.filter((value): value is string => typeof value === "string");
      if (!Number.isInteger(roomId)) return null;
      return { roomId, playerIds };
    })
    .filter((room): room is HouseMingleRoomAssignment => room !== null);

  return {
    rooms,
    rationale: typeof parsed.rationale === "string" ? parsed.rationale : undefined,
    thinking: typeof parsed.thinking === "string" ? parsed.thinking : undefined,
    reasoningContext: typeof parsed.reasoningContext === "string" ? parsed.reasoningContext : undefined,
  };
}

function readString(value: unknown, fallback = ""): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function readNullableString(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function readStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim())
    .filter(Boolean);
}

function readConfidence(value: unknown): HouseConfidence {
  return value === "high" || value === "medium" || value === "low" ? value : "low";
}

function readAllianceStatus(value: unknown): HouseAllianceHypothesis["status"] {
  return value === "forming" ||
    value === "active" ||
    value === "fracturing" ||
    value === "retired" ||
    value === "speculative"
    ? value
    : "speculative";
}

function readStoryStatus(value: unknown): HouseStoryArc["status"] {
  return value === "emerging" || value === "active" || value === "resolved" || value === "dropped"
    ? value
    : "emerging";
}

function readRecordArray(value: unknown): Record<string, unknown>[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is Record<string, unknown> =>
    item !== null && typeof item === "object" && !Array.isArray(item),
  );
}

function readCoveredWindow(value: unknown, fallback: HouseCoveredWindow): HouseCoveredWindow {
  if (!value || typeof value !== "object" || Array.isArray(value)) return fallback;
  const record = value as Record<string, unknown>;
  const fromRound = typeof record.fromRound === "number" && Number.isFinite(record.fromRound)
    ? record.fromRound
    : fallback.fromRound;
  const toRound = typeof record.toRound === "number" && Number.isFinite(record.toRound)
    ? record.toRound
    : fallback.toRound;
  const fromPhase = typeof record.fromPhase === "string" && record.fromPhase in Phase
    ? record.fromPhase as Phase
    : fallback.fromPhase;
  const toPhase = typeof record.toPhase === "string" && record.toPhase in Phase
    ? record.toPhase as Phase
    : fallback.toPhase;
  return {
    fromRound,
    toRound,
    ...(fromPhase && { fromPhase }),
    ...(toPhase && { toPhase }),
  };
}

function normalizeAlliances(value: unknown): HouseAllianceHypothesis[] {
  return readRecordArray(value).map((record, index) => ({
    name: readString(record.name, `Unnamed alliance ${index + 1}`),
    members: readStringArray(record.members),
    status: readAllianceStatus(record.status),
    confidence: readConfidence(record.confidence),
    evidence: readStringArray(record.evidence),
    tension: readNullableString(record.tension),
    openQuestions: readStringArray(record.openQuestions),
  }));
}

function normalizePlayerTrajectories(value: unknown): HousePlayerTrajectory[] {
  return readRecordArray(value).map((record) => ({
    playerName: readString(record.playerName, "Unknown"),
    currentRead: readString(record.currentRead, "No clear House read yet."),
    pressurePoints: readStringArray(record.pressurePoints),
    likelyNextMove: readNullableString(record.likelyNextMove),
  }));
}

function normalizeStoryArcs(value: unknown): HouseStoryArc[] {
  return readRecordArray(value).map((record, index) => ({
    title: readString(record.title, `Story arc ${index + 1}`),
    summary: readString(record.summary, "No summary provided."),
    involvedPlayers: readStringArray(record.involvedPlayers),
    status: readStoryStatus(record.status),
  }));
}

function parseHouseStrategyBible(
  raw: string,
  context: HouseStrategyBibleUpdateContext,
): HouseStrategyBibleUpdateResult {
  const parsed = extractJsonObject(raw);
  if (!parsed) {
    return { packet: null, rationale: "House Strategy Bible response was not parseable JSON." };
  }

  const previous = context.previousPacket;
  const packetRecord = parsed.packet && typeof parsed.packet === "object" && !Array.isArray(parsed.packet)
    ? parsed.packet as Record<string, unknown>
    : parsed;
  const previousRevisionId = previous?.revisionId ?? null;
  const revisionId = readString(
    packetRecord.revisionId,
    `house-r${context.round}-${context.phase.toLowerCase()}-${previous ? "rev" : "initial"}`,
  );

  const packet: HouseStrategyBiblePacket = {
    revisionId,
    previousRevisionId: readNullableString(packetRecord.previousRevisionId) ?? previousRevisionId,
    updatedAtRound: context.round,
    updatedAtPhase: context.phase,
    coveredWindow: readCoveredWindow(packetRecord.coveredWindow, context.coveredWindow),
    summary: readString(packetRecord.summary, "The House is still forming its read of the game."),
    alliances: normalizeAlliances(packetRecord.alliances),
    tensions: readStringArray(packetRecord.tensions),
    promises: readStringArray(packetRecord.promises),
    voteBlocs: readStringArray(packetRecord.voteBlocs),
    mingleDiscoveries: readStringArray(packetRecord.mingleDiscoveries),
    playerTrajectories: normalizePlayerTrajectories(packetRecord.playerTrajectories),
    storyArcs: normalizeStoryArcs(packetRecord.storyArcs),
    droppedThreads: readStringArray(packetRecord.droppedThreads),
    openQuestions: readStringArray(packetRecord.openQuestions),
    changedSincePrevious: readString(packetRecord.changedSincePrevious, previous ? "Updated House read." : "Initial House read."),
  };

  return {
    packet,
    rationale: readNullableString(parsed.rationale) ?? undefined,
    thinking: readNullableString(parsed.thinking) ?? undefined,
    reasoningContext: readNullableString(parsed.reasoningContext) ?? undefined,
  };
}

function parseHouseSummary(
  raw: string,
  context: HouseGameplaySummaryContext,
): HouseGameplaySummaryResult {
  const parsed = extractJsonObject(raw);
  if (!parsed) {
    return {
      summary: raw.trim() || `Round ${context.round}: The House is watching the pressure shift.`,
      kind: context.kind,
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: [],
    };
  }

  return {
    summary: readString(parsed.summary, `Round ${context.round}: The House is watching the pressure shift.`),
    kind: context.kind,
    packetRevisionId: context.packet?.revisionId ?? null,
    coveredWindow: readCoveredWindow(parsed.coveredWindow, context.coveredWindow),
    referencedAllianceNames: readStringArray(parsed.referencedAllianceNames),
    openQuestions: readStringArray(parsed.openQuestions),
    thinking: readNullableString(parsed.thinking) ?? undefined,
    reasoningContext: readNullableString(parsed.reasoningContext) ?? undefined,
  };
}

function parseHouseProducerBrief(
  raw: string,
  context: DiaryRoomContext,
  packet: HouseStrategyBiblePacket | null,
): HouseProducerBrief {
  const parsed = extractJsonObject(raw) ?? {};
  return {
    playerName: context.agentName,
    packetRevisionId: packet?.revisionId ?? null,
    storyRole: readString(parsed.storyRole, `${context.agentName} is still defining their role in the game.`),
    pressurePoints: readStringArray(parsed.pressurePoints),
    relevantAllianceHypotheses: readStringArray(parsed.relevantAllianceHypotheses),
    contradictions: readStringArray(parsed.contradictions),
    questionAngles: readStringArray(parsed.questionAngles),
    safeToReveal: readStringArray(parsed.safeToReveal),
    privateDoNotReveal: readStringArray(parsed.privateDoNotReveal),
    thinking: readNullableString(parsed.thinking) ?? undefined,
    reasoningContext: readNullableString(parsed.reasoningContext) ?? undefined,
  };
}

export class LLMHouseInterviewer implements IHouseInterviewer {
  private readonly openai: OpenAI;
  private readonly model: string;
  private readonly providerProfileId: ProviderProfileId;
  private readonly catalogId?: string;
  private readonly modelCapabilities: ModelRequestCapabilities;
  private readonly reasoningPolicy: ModelReasoningPolicy;
  private readonly privateTraceSink?: PrivateTraceSink;
  private readonly privateTraceGameId?: UUID;
  private readonly privateTraceOwnerEpoch?: string;
  private readonly toolChoiceMode: LlmToolChoiceMode;
  private readonly structuredOutputTimeoutMs: number;
  private tokenTracker: TokenTracker | null = null;

  constructor(openaiClient: OpenAI, model = "gpt-5-nano", options: LLMHouseInterviewerOptions = {}) {
    this.openai = openaiClient;
    this.model = model;
    this.providerProfileId = options.providerProfileId ?? "openai";
    this.catalogId = options.catalogId;
    this.modelCapabilities = options.modelCapabilities ?? inferModelCapabilities(model, this.providerProfileId);
    this.reasoningPolicy = options.reasoningPolicy ?? "action-policy";
    this.privateTraceSink = options.privateTraceSink;
    this.privateTraceGameId = options.gameId;
    this.privateTraceOwnerEpoch = options.ownerEpoch;
    this.toolChoiceMode = options.toolChoiceMode ?? "named";
    this.structuredOutputTimeoutMs = options.structuredOutputTimeoutMs ?? 45_000;
  }

  /** Attach a token tracker to record LLM usage. */
  setTokenTracker(tracker: TokenTracker): void {
    this.tokenTracker = tracker;
  }

  private recordUsage(source: string, response: ChatCompletion): void {
    if (!this.tokenTracker) return;
    const usage = LLMHouseInterviewer.providerUsageMetadata(response);
    if (!usage || usage.promptTokens === undefined || usage.completionTokens === undefined) return;
    this.tokenTracker.record(
      source,
      usage.promptTokens,
      usage.completionTokens,
      usage.cachedTokens ?? 0,
      usage.reasoningTokens ?? 0,
    );
  }

  private privateTraceContext(action: string, round: number, phase: Phase): PrivateDecisionTraceContext {
    return {
      ...(this.privateTraceGameId && { gameId: this.privateTraceGameId }),
      ...(this.privateTraceOwnerEpoch && { ownerEpoch: this.privateTraceOwnerEpoch }),
      action,
      actor: {
        name: "The House",
        role: "house",
      },
      phase,
      round,
    };
  }

  private static privateTraceMessages(
    messages: readonly { role: string; content: unknown; name?: string }[],
  ): PrivateDecisionTraceMessage[] {
    return messages.map((message) => ({
      role: message.role,
      content: message.content,
      ...(message.name && { name: message.name }),
    }));
  }

  private static privateTraceToolCalls(message: unknown): PrivateDecisionTraceToolCall[] | undefined {
    if (!message || typeof message !== "object" || Array.isArray(message)) return undefined;
    const record = message as Record<string, unknown>;
    if (!Array.isArray(record.tool_calls)) return undefined;
    const toolCalls = record.tool_calls
      .map((toolCall): PrivateDecisionTraceToolCall | null => {
        if (!toolCall || typeof toolCall !== "object" || Array.isArray(toolCall)) return null;
        const toolRecord = toolCall as Record<string, unknown>;
        const functionRecord =
          toolRecord.function && typeof toolRecord.function === "object" && !Array.isArray(toolRecord.function)
            ? toolRecord.function as Record<string, unknown>
            : {};
        return {
          ...(typeof toolRecord.id === "string" && { id: toolRecord.id }),
          ...(typeof toolRecord.type === "string" && { type: toolRecord.type }),
          ...(typeof functionRecord.name === "string" && { name: functionRecord.name }),
          ...(typeof functionRecord.arguments === "string" && { arguments: functionRecord.arguments }),
        };
      })
      .filter((toolCall): toolCall is PrivateDecisionTraceToolCall => toolCall !== null);
    return toolCalls.length > 0 ? toolCalls : undefined;
  }

  private static extractReasoningContext(message: unknown): string {
    if (!message || typeof message !== "object" || Array.isArray(message)) return "";
    const record = message as Record<string, unknown>;
    return readString(record.reasoning_content) || readString(record.reasoning);
  }

  private static readNumberField(value: unknown): number | undefined {
    return typeof value === "number" && Number.isFinite(value) ? value : undefined;
  }

  private static providerUsageMetadata(response: ChatCompletion): PrivateDecisionTrace["usage"] | undefined {
    const usage = (response as unknown as Record<string, unknown>).usage;
    if (!usage || typeof usage !== "object" || Array.isArray(usage)) return undefined;
    const usageRecord = usage as Record<string, unknown>;
    const completionDetails = usageRecord.completion_tokens_details &&
      typeof usageRecord.completion_tokens_details === "object" &&
      !Array.isArray(usageRecord.completion_tokens_details)
      ? usageRecord.completion_tokens_details as Record<string, unknown>
      : {};
    const promptDetails = usageRecord.prompt_tokens_details &&
      typeof usageRecord.prompt_tokens_details === "object" &&
      !Array.isArray(usageRecord.prompt_tokens_details)
      ? usageRecord.prompt_tokens_details as Record<string, unknown>
      : {};
    const routerBilling = usageRecord.imgnai &&
      typeof usageRecord.imgnai === "object" &&
      !Array.isArray(usageRecord.imgnai)
      ? usageRecord.imgnai as Record<string, unknown>
      : undefined;
    const diagnostics = "imgnai" in usageRecord && !routerBilling ? ["malformed_router_billing"] : [];
    const metadata: NonNullable<PrivateDecisionTrace["usage"]> = {
      ...(LLMHouseInterviewer.readNumberField(usageRecord.prompt_tokens) !== undefined && { promptTokens: LLMHouseInterviewer.readNumberField(usageRecord.prompt_tokens) }),
      ...(LLMHouseInterviewer.readNumberField(usageRecord.completion_tokens) !== undefined && { completionTokens: LLMHouseInterviewer.readNumberField(usageRecord.completion_tokens) }),
      ...(LLMHouseInterviewer.readNumberField(promptDetails.cached_tokens) !== undefined && { cachedTokens: LLMHouseInterviewer.readNumberField(promptDetails.cached_tokens) }),
      ...(LLMHouseInterviewer.readNumberField(completionDetails.reasoning_tokens) !== undefined && { reasoningTokens: LLMHouseInterviewer.readNumberField(completionDetails.reasoning_tokens) }),
      ...(LLMHouseInterviewer.readNumberField(usageRecord.total_tokens) !== undefined && { totalTokens: LLMHouseInterviewer.readNumberField(usageRecord.total_tokens) }),
      ...(routerBilling && { routerBilling }),
      ...(diagnostics.length > 0 && { diagnostics }),
    };
    return Object.keys(metadata).length > 0 ? metadata : undefined;
  }

  private async emitPrivateDecisionTrace(params: {
    context: PrivateDecisionTraceContext;
    messages: readonly { role: string; content: unknown; name?: string }[];
    response: ChatCompletion;
    output?: unknown;
  }): Promise<void> {
    if (!this.privateTraceSink) return;
    const choice = params.response.choices[0];
    const message = choice?.message;
    const outputRecord =
      params.output && typeof params.output === "object" && !Array.isArray(params.output)
        ? params.output as Record<string, unknown>
        : {};
    const emittedThinking = readString(outputRecord.thinking);
    const reasoningContext =
      readString(outputRecord.reasoningContext) ||
      LLMHouseInterviewer.extractReasoningContext(message);
    const toolCalls = LLMHouseInterviewer.privateTraceToolCalls(message);
    const content = typeof message?.content === "string" ? message.content : null;
    const requestedReasoningEffort = this.requestedReasoningEffort();
    const privateTraceMessages = LLMHouseInterviewer.privateTraceMessages(params.messages);
    const trace: PrivateDecisionTrace = {
      version: 2,
      ...(params.context.gameId && { gameId: params.context.gameId }),
      ...(params.context.ownerEpoch && { ownerEpoch: params.context.ownerEpoch }),
      action: params.context.action,
      actor: params.context.actor,
      ...(params.context.phase && { phase: params.context.phase }),
      ...(params.context.round !== undefined && { round: params.context.round }),
      createdAt: new Date().toISOString(),
      model: {
        provider: this.providerProfileId,
        providerProfileId: this.providerProfileId,
        ...(this.catalogId && { catalogId: this.catalogId }),
        name: this.model,
      },
      ...(requestedReasoningEffort && { requestedReasoningEffort }),
      reasoningPolicy: this.reasoningPolicy,
      prompt: {
        messages: privateTraceMessages,
      },
      request: {
        providerProfileId: this.providerProfileId,
        ...(this.catalogId && { catalogId: this.catalogId }),
        model: this.model,
        messages: privateTraceMessages,
        ...(requestedReasoningEffort && { reasoning_effort: requestedReasoningEffort }),
        reasoningPolicy: this.reasoningPolicy,
      },
      response: {
        raw: params.response,
        finishReason: choice?.finish_reason ?? null,
        content,
        ...(toolCalls && { toolCalls }),
      },
      ...(params.output !== undefined && { output: params.output }),
      ...(LLMHouseInterviewer.providerUsageMetadata(params.response) && { usage: LLMHouseInterviewer.providerUsageMetadata(params.response) }),
      ...(emittedThinking && { emittedThinking }),
      ...(reasoningContext && { reasoningContext }),
      ...(params.context.boundary && { boundary: params.context.boundary }),
    };

    try {
      await this.privateTraceSink(trace);
    } catch (error) {
      console.warn(`[trace-sink] house action=${trace.action} failed:`, error);
    }
  }

  private requestedReasoningEffort(): ModelReasoningEffort | undefined {
    if (!this.modelCapabilities.supportsReasoningEffort) return undefined;
    if (this.reasoningPolicy === "low" || this.reasoningPolicy === "medium" || this.reasoningPolicy === "high") {
      return this.reasoningPolicy;
    }
    return undefined;
  }

  private modelParams(maxTokens: number, temperature: number) {
    const usesReasoningBudget = this.modelCapabilities.supportsReasoningEffort || this.modelCapabilities.usesMaxCompletionTokens;
    const budget = usesReasoningBudget ? maxTokens + 4000 : maxTokens;
    const reasoningEffort = this.requestedReasoningEffort();
    return {
      ...(this.modelCapabilities.usesMaxCompletionTokens
        ? { max_completion_tokens: budget }
        : { max_tokens: budget }),
      ...(this.modelCapabilities.supportsTemperature && { temperature }),
      ...(reasoningEffort && { reasoning_effort: reasoningEffort }),
    };
  }

  private usesLocalStructuredCompatibility(): boolean {
    return this.toolChoiceMode !== "named";
  }

  private localStructuredMinTokens(): number {
    const configured =
      process.env.INFLUENCE_LLM_LOCAL_STRUCTURED_MIN_TOKENS ??
      process.env.INFLUENCE_LLM_STRUCTURED_MIN_TOKENS;
    const parsed = configured ? parseInt(configured, 10) : NaN;
    return Number.isFinite(parsed) && parsed > 0 ? parsed : 4096;
  }

  private applyStructuredTokenFloor(maxTokens: number): number {
    if (!this.usesLocalStructuredCompatibility()) return maxTokens;
    return Math.max(maxTokens, this.localStructuredMinTokens());
  }

  private structuredOutputSignal(): AbortSignal | undefined {
    if (this.structuredOutputTimeoutMs < 1) return undefined;
    return AbortSignal.timeout(this.structuredOutputTimeoutMs);
  }

  private parseStructuredJsonContent(content: string | null | undefined): Record<string, unknown> | null {
    const text = content?.trim();
    if (!text) return null;
    try {
      const parsed = JSON.parse(text) as unknown;
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
      return parsed as Record<string, unknown>;
    } catch {
      return extractJsonObject(text);
    }
  }

  private async callHouseJsonSchema(params: {
    action: string;
    source: string;
    round: number;
    phase: Phase;
    messages: Array<{ role: "system" | "user"; content: string }>;
    schemaName: string;
    schema: Record<string, unknown>;
    maxTokens: number;
    temperature: number;
  }): Promise<{ parsed: Record<string, unknown>; response: ChatCompletion }> {
    let effectiveMaxTokens = this.applyStructuredTokenFloor(params.maxTokens);
    const maxAttempts = 2;
    let lastError: Error | null = null;
    let lastResponse: ChatCompletion | null = null;

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        const response = await this.openai.chat.completions.create(
          {
            model: this.model,
            messages: params.messages,
            response_format: {
              type: "json_schema",
              json_schema: {
                name: params.schemaName,
                strict: true,
                schema: params.schema,
              },
            },
            ...this.modelParams(effectiveMaxTokens, params.temperature),
          },
          { signal: this.structuredOutputSignal() },
        );
        lastResponse = response;
        this.recordUsage(params.source, response);

        const choice = response.choices[0];
        if (choice?.message?.refusal) {
          throw new Error("model_refusal");
        }
        if (choice?.finish_reason === "content_filter") {
          throw new Error("content_filter");
        }
        if (choice?.finish_reason === "length") {
          throw new Error("length");
        }

        const parsed = this.parseStructuredJsonContent(choice?.message?.content);
        if (!parsed) {
          throw new Error("invalid_json");
        }
        return { parsed, response };
      } catch (error) {
        lastError = error instanceof Error ? error : new Error(String(error));
        const isNonRetryable =
          lastError.message === "model_refusal" ||
          lastError.message === "content_filter" ||
          lastError.message === "request_aborted" ||
          lastError.name === "APIUserAbortError" ||
          lastError.name === "AbortError";
        const shouldRetry = attempt < maxAttempts && !isNonRetryable;
        if (!shouldRetry) break;
        if (lastError.message === "length" || lastError.message === "invalid_json") {
          effectiveMaxTokens = Math.ceil(effectiveMaxTokens * 1.5);
        }
        console.warn(`[house-structured-output] action=${params.action} attempt ${attempt} failed, retrying: ${lastError.message}`);
      }
    }

    const failure = lastError ?? new Error("unknown_failure");
    if (lastResponse) {
      await this.emitPrivateDecisionTrace({
        context: this.privateTraceContext(params.action, params.round, params.phase),
        messages: params.messages,
        response: lastResponse,
        output: { error: failure.message },
      });
    }
    console.warn(`[house-structured-output] action=${params.action} failed: ${failure.message}`);
    throw failure;
  }

  async assignMingleRooms(context: HouseMingleAssignmentContext): Promise<HouseMingleAssignmentResult> {
    const playerLines = context.players
      .map((player) => {
        const intent = player.intent;
        const intentText = intent
          ? [
              `seek=${intent.seekPlayers.length > 0 ? intent.seekPlayers.join(", ") : "none"}`,
              `avoid=${intent.avoidPlayers.length > 0 ? intent.avoidPlayers.join(", ") : "none"}`,
              `preferredSize=${intent.preferredRoomSize}`,
              `purpose=${intent.purpose || "not stated"}`,
              `provisionalTarget=${intent.provisionalTarget ?? "none"}`,
              `noTargetReason=${intent.noTargetReason ?? "n/a"}`,
              `openingAsk=${intent.openingAsk || "not stated"}`,
              `strategicLens=${intent.strategicLens}`,
              `lensRationale=${intent.strategicLensRationale || "not stated"}`,
            ].join("; ")
          : "no intent available";
        return `- ${player.name} (${player.id}): ${intentText}`;
      })
      .join("\n");

    const roomList = Array.from({ length: context.roomCount }, (_, index) => index + 1).join(", ");
    const prompt = `Assign initial Mingle rooms for Round ${context.round}.

Rooms available: ${roomList}
Alive players and hidden Mingle intents:
${playerLines}

Your job:
- Form interesting, strategic, roughly balanced rooms from seek/avoid/preferred-size/purpose signals.
- Prefer rooms that create useful conversations: tests, coalition repair, pressure checks, information trades, and unresolved tensions.
- Do not hide everyone in Room 1. Room numbers are neutral containers; assign people based on the full set of intents.
- Assign every listed player exactly once.
- Use only the exact player IDs above and room IDs from the available room list.

Respond with JSON only:
{
  "rooms": [
    { "roomId": 1, "playerIds": ["player-id"] }
  ],
  "rationale": "short producer/debug rationale for the allocation"
    }`;

    try {
      const messages = [
        { role: "system" as const, content: "You are the House producer assigning private Mingle rooms. Return JSON only." },
        { role: "user" as const, content: prompt },
      ];
      const { parsed, response } = await this.callHouseJsonSchema({
        action: "house-mingle-assignment",
        source: "House/mingle-assignment",
        round: context.round,
        phase: Phase.MINGLE,
        messages,
        schemaName: "house_mingle_assignment",
        schema: {
          type: "object",
          properties: {
            rooms: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  roomId: { type: "integer" },
                  playerIds: {
                    type: "array",
                    items: { type: "string" },
                  },
                },
                required: ["roomId", "playerIds"],
                additionalProperties: false,
              },
            },
            rationale: { type: "string" },
            thinking: { type: ["string", "null"] },
          },
          required: ["rooms", "rationale", "thinking"],
          additionalProperties: false,
        },
        maxTokens: 1200,
        temperature: 0.4,
      });

      const output = parseHouseMingleAssignmentRecord({
        ...parsed,
        reasoningContext: readString(parsed.reasoningContext) || LLMHouseInterviewer.extractReasoningContext(response.choices[0]?.message),
      });
      await this.emitPrivateDecisionTrace({
        context: this.privateTraceContext("house-mingle-assignment", context.round, Phase.MINGLE),
        messages,
        response,
        output,
      });
      return output;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        rooms: [],
        rationale: `House assignment failed; deterministic fallback will assign rooms (${message}).`,
      };
    }
  }

  async updateStrategyBible(context: HouseStrategyBibleUpdateContext): Promise<HouseStrategyBibleUpdateResult> {
    const evidence = this.formatHouseEvidence(context.evidence);
    const previousPacket = context.previousPacket
      ? JSON.stringify(context.previousPacket, null, 2)
      : "(none yet; create the first House Strategy Bible Packet)";

    const prompt = `Update the private House Strategy Bible Packet for Influence.

Round: ${context.round}
Phase boundary: ${context.phase}
Covered window: R${context.coveredWindow.fromRound}-${context.coveredWindow.toRound}

Previous packet:
${previousPacket}

Producer evidence:
${evidence}

Your job:
- Carry forward prior useful reads; do not silently forget unresolved threads.
- Name alliances only as producer hypotheses, with confidence and evidence.
- Revise, fracture, retire, or lower confidence when votes, eliminations, diary answers, or room behavior contradict prior reads.
- Authoritative round facts and the current player lists override the previous packet. If the previous packet conflicts about alive/eliminated players, active shields, the current/last empowered player, Council candidates, or the latest elimination, rewrite it as stale history or drop it.
- Active shields are only active if listed as active in Producer evidence. Historical shield grants must be described as past/expired unless the current active shield list says otherwise.
- Do not describe an older eliminated player as the fresh wound after a later Council has resolved.
- Track tensions, promises, vote blocs, Mingle discoveries, player trajectories, story arcs, dropped threads, and open questions.
- Do not treat House hypotheses as canonical truth.

Respond with JSON only:
{
  "packet": {
    "revisionId": "house-r${context.round}-${context.phase.toLowerCase()}-1",
    "previousRevisionId": ${context.previousPacket ? `"${context.previousPacket.revisionId}"` : "null"},
    "coveredWindow": { "fromRound": ${context.coveredWindow.fromRound}, "toRound": ${context.coveredWindow.toRound}, "toPhase": "${context.phase}" },
    "summary": "compact producer read of the game",
    "alliances": [
      {
        "name": "short memorable alliance hypothesis name",
        "members": ["Player"],
        "status": "speculative|forming|active|fracturing|retired",
        "confidence": "low|medium|high",
        "evidence": ["specific evidence"],
        "tension": "optional fracture or pressure",
        "openQuestions": ["what the House still needs to know"]
      }
    ],
    "tensions": ["active tensions"],
    "promises": ["pending or broken promises"],
    "voteBlocs": ["vote coordination reads"],
    "mingleDiscoveries": ["notable room discoveries"],
    "playerTrajectories": [
      { "playerName": "Player", "currentRead": "trajectory", "pressurePoints": ["pressure"], "likelyNextMove": "optional" }
    ],
    "storyArcs": [
      { "title": "arc name", "summary": "what is developing", "involvedPlayers": ["Player"], "status": "emerging|active|resolved|dropped" }
    ],
    "droppedThreads": ["threads that no longer matter"],
    "openQuestions": ["questions for future summaries and diaries"],
    "changedSincePrevious": "what changed from the previous packet"
  },
  "rationale": "short producer/debug rationale",
  "thinking": "brief hidden producer thinking"
    }`;

    try {
      const messages = [
        { role: "system" as const, content: "You are The House producer maintaining a private Strategy Bible. Return JSON only." },
        { role: "user" as const, content: prompt },
      ];
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages,
        response_format: { type: "json_object" },
        ...this.modelParams(5000, 0.35),
      });
      this.recordUsage("House/strategy-bible", response);

      const output = parseHouseStrategyBible(response.choices[0]?.message?.content?.trim() ?? "", context);
      await this.emitPrivateDecisionTrace({
        context: this.privateTraceContext("house-strategy-bible", context.round, context.phase),
        messages,
        response,
        output,
      });
      return output;
    } catch (err) {
      return {
        packet: null,
        rationale: `House Strategy Bible update failed (${err instanceof Error ? err.message : String(err)}).`,
      };
    }
  }

  async generateHouseSummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    const prompt = this.buildSummaryPrompt(context, "Generate a concise, watchable 3-5 sentence House MC summary for the audience.");
    try {
      const messages = [
        { role: "system" as const, content: "You are the House MC — omniscient, dramatic reality TV narrator. Return JSON only." },
        { role: "user" as const, content: prompt },
      ];
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages,
        response_format: { type: "json_object" },
        ...this.modelParams(1600, 0.8),
      });
      this.recordUsage("House/mc-summary", response);
      const output = parseHouseSummary(response.choices[0]?.message?.content?.trim() ?? "", context);
      await this.emitPrivateDecisionTrace({
        context: this.privateTraceContext("house-summary", context.round, context.phase),
        messages,
        response,
        output,
      });
      return output;
    } catch {
      return this.templateSummary(context, "The House is watching closely as the game narrows and the pressure shifts.");
    }
  }

  async generateLongFormGameplaySummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    const prompt = this.buildSummaryPrompt(
      context,
      "Generate a long-form producer catch-up summary. Explain teams forming or weakening, leverage shifts, unresolved promises, and House open questions.",
    );
    try {
      const messages = [
        { role: "system" as const, content: "You are The House showrunner writing a private/audience catch-up for producer review. Return JSON only." },
        { role: "user" as const, content: prompt },
      ];
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages,
        response_format: { type: "json_object" },
        ...this.modelParams(4000, 0.75),
      });
      this.recordUsage("House/long-form-summary", response);
      const output = parseHouseSummary(response.choices[0]?.message?.content?.trim() ?? "", context);
      await this.emitPrivateDecisionTrace({
        context: this.privateTraceContext("house-long-form-summary", context.round, context.phase),
        messages,
        response,
        output,
      });
      return output;
    } catch {
      return this.templateSummary(context, "The long-form House read is unavailable, but the game continues to turn on shifting promises and pressure.");
    }
  }

  async generateProducerBrief(
    context: DiaryRoomContext,
    packet: HouseStrategyBiblePacket | null,
  ): Promise<HouseProducerBrief> {
    const packetText = packet ? JSON.stringify(packet, null, 2) : "(no House Strategy Bible Packet yet)";
    const prompt = `Create a private producer brief before The House interviews ${context.agentName}.

Current diary context:
${this.buildGameStatePrompt(context)}

Canonical fact contract:
${this.buildCanonicalFactContract(context)}

Current House Strategy Bible Packet:
${packetText}

Your job:
- Identify ${context.agentName}'s current story role.
- Name pressure points, relevant alliance hypotheses, contradictions, and sharp question angles.
- Separate safe-to-reveal material from private producer reads that must not be dumped into the visible question.
- Treat the diary context and Canonical fact contract as authoritative over the House Strategy Bible Packet.
- If the packet conflicts about active shields, who is empowered, who is alive/eliminated, current council status, or the latest elimination, mark that packet claim as stale history and do not repeat it as live truth.
- The visible question may needle the player, but it must not reveal hidden House packet content as fact.

Respond with JSON only:
{
  "storyRole": "short role",
  "pressurePoints": ["pressure"],
  "relevantAllianceHypotheses": ["alliance hypothesis names or reads"],
  "contradictions": ["contradictions to probe"],
  "questionAngles": ["specific angles The House can ask about"],
  "safeToReveal": ["safe player-known facts or carefully framed pressure"],
  "privateDoNotReveal": ["hidden producer reads not to disclose directly"],
  "thinking": "brief hidden producer thinking"
    }`;

    try {
      const messages = [
        { role: "system" as const, content: "You are The House producer preparing a private diary-room brief. Return JSON only." },
        { role: "user" as const, content: prompt },
      ];
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages,
        response_format: { type: "json_object" },
        ...this.modelParams(1800, 0.55),
      });
      this.recordUsage("House/producer-brief", response);
      const output = parseHouseProducerBrief(response.choices[0]?.message?.content?.trim() ?? "", context, packet);
      await this.emitPrivateDecisionTrace({
        context: this.privateTraceContext("house-producer-brief", context.round, Phase.DIARY_ROOM),
        messages,
        response,
        output,
      });
      return output;
    } catch {
      return parseHouseProducerBrief("", context, packet);
    }
  }

  async generateQuestion(context: DiaryRoomContext): Promise<string> {
    const gameStatePrompt = this.buildGameStatePrompt(context);
    const messages = [
      { role: "system" as const, content: HOUSE_PERSONALITY },
      { role: "user" as const, content: gameStatePrompt },
    ];

    const response = await this.openai.chat.completions.create({
      model: this.model,
      messages,
      ...this.modelParams(150, 0.9),
    });

    this.recordUsage("House/question", response);

    const question = response.choices[0]?.message?.content?.trim();
    const output = question && question.length > 0
      ? question
      : `${context.agentName}, what's on your mind right now?`;
    await this.emitPrivateDecisionTrace({
      context: this.privateTraceContext("house-question", context.round, Phase.DIARY_ROOM),
      messages,
      response,
      output: { question: output },
    });
    return output;
  }

  async generateFollowUpOrClose(
    context: DiaryRoomContext,
    conversationSoFar: Array<{ question: string; answer: string }>,
  ): Promise<FollowUpResult> {
    const gameStatePrompt = this.buildGameStatePrompt(context);
    const exchangeCount = conversationSoFar.length;

    const convoText = conversationSoFar
      .map((e, i) => `  Q${i + 1}: "${e.question}"\n  A${i + 1}: "${e.answer}"`)
      .join("\n");

    const followUpPrompt = `${gameStatePrompt}

## This Session's Conversation So Far (${exchangeCount} exchanges)
${convoText}

## Your Decision
You have asked ${exchangeCount} question(s) so far this session. You may ask up to 4 total.
Decide: should you ask ANOTHER follow-up question, or wrap up the session?

Ask another question if:
- The player said something that contradicts what they said in a PREVIOUS diary entry — call it out
- They named or avoided naming a specific player — probe WHY
- They revealed a plan — challenge it: "What if [name] doesn't cooperate?"
- They showed emotion — push on it: "That sounded personal. Is it?"

Wrap up if:
- You've gotten a real confession, emotional moment, or strategic reveal
- The player is giving you nothing — evasive or robotic answers
- You've asked 3+ questions already

Your follow-up MUST reference something specific from their answer — a name they mentioned, a claim they made, an emotion they showed. Never ask a generic follow-up.

Respond with EXACTLY one of these formats:
FOLLOW_UP: <your next question>
CLOSE: <your brief closing remark to the player, 1 sentence>`;
    const messages = [
      { role: "system" as const, content: HOUSE_PERSONALITY },
      { role: "user" as const, content: followUpPrompt },
    ];

    const response = await this.openai.chat.completions.create({
      model: this.model,
      messages,
      ...this.modelParams(200, 0.8),
    });

    this.recordUsage("House/followup", response);

    const raw = response.choices[0]?.message?.content?.trim() ?? "";

    let output: FollowUpResult;
    if (raw.startsWith("FOLLOW_UP:")) {
      output = { type: "question", question: raw.slice("FOLLOW_UP:".length).trim() };
    } else if (raw.startsWith("CLOSE:")) {
      output = { type: "close", message: raw.slice("CLOSE:".length).trim() };
    } else {
      // If the LLM didn't follow the format, treat as a close
      output = { type: "close", message: raw || `Thank you, ${context.agentName}. The House sees all.` };
    }

    await this.emitPrivateDecisionTrace({
      context: this.privateTraceContext("house-followup", context.round, Phase.DIARY_ROOM),
      messages,
      response,
      output,
    });
    return output;
  }

  private formatActiveShields(names: string[]): string {
    return names.length > 0 ? names.join(", ") : "none";
  }

  private formatCouncilRoleForPrompt(role: HouseCouncilRoleFact | null | undefined): string {
    if (!role || role.role === "not_applicable") return "none";
    const candidates = role.candidateNames ? role.candidateNames.join(" vs ") : "unknown candidates";
    switch (role.role) {
      case "candidate":
        return `Council candidate/on the block (${candidates}); did not cast a Council vote.`;
      case "voted_for_eliminated":
        return `Council voter for eliminated player ${role.eliminatedName ?? role.votedForName ?? "unknown"}.`;
      case "voted_for_survivor":
        return `Council voter for surviving candidate ${role.votedForName ?? role.survivingCandidateName ?? "unknown"}.`;
      case "empowered_tiebreaker":
        return `Empowered tiebreaker-only Council choice: ${role.votedForName ?? "unknown"}.`;
      case "empowered_no_tiebreak_needed":
        return `Empowered player; Council resolved without needing your tiebreaker.`;
      case "non_voter":
        return `No Council ballot recorded; candidates were ${candidates}.`;
    }
  }

  private buildCanonicalFactContract(context: DiaryRoomContext): string {
    const roundFacts = context.roundFacts;
    const latestEliminated = roundFacts?.eliminatedName
      ?? roundFacts?.autoEliminatedName
      ?? context.lastEliminated
      ?? "none";
    return `- Canonical game state overrides House Strategy Bible, producer hypotheses, player memory, and prior summaries.
- Active shields right now: ${this.formatActiveShields(context.activeShieldNames)}.
- Current/last resolved empowered player: ${context.empoweredName ?? "none"}.
- Latest eliminated player for this context: ${latestEliminated}.
- If older material says a different player is currently empowered, shielded, alive, eliminated, freshly gone, or in live Council danger, treat that older material as stale history.
- Do not describe historical shields as active. If no active shield is listed, do not say anyone is shielded or a shield anchor.
- If Council has just resolved, there is no live Council candidate remaining inside Diary Room; any candidates are historical/resolved only.`;
  }

  private buildGameStatePrompt(context: DiaryRoomContext): string {
    const {
      precedingPhase,
      round,
      agentName,
      alivePlayers,
      activeShieldNames,
      eliminatedPlayers,
      lastEliminated,
      empoweredName,
      councilCandidates,
      recentMessages,
      previousDiaryEntries,
      playerMessages,
      roundFacts,
      councilRole,
    } = context;

    const recentMsgText = recentMessages
      .slice(-8)
      .map((m) => `  [${m.phase}] ${m.from}: "${m.text}"`)
      .join("\n");

    // What this specific player said recently
    const playerMsgText = (playerMessages ?? [])
      .slice(-5)
      .map((m) => `  [${m.phase}] "${m.text}"`)
      .join("\n");

    // Previous diary Q&A for follow-up continuity
    const prevDiaryText = (previousDiaryEntries ?? [])
      .slice(-2)
      .map((d) => `  Round ${d.round} — Q: "${d.question}" A: "${d.answer}"`)
      .join("\n");
    const latestEliminatedName = roundFacts?.eliminatedName ?? roundFacts?.autoEliminatedName ?? lastEliminated;

    let situationContext = "";
    switch (precedingPhase) {
      case Phase.INTRODUCTION:
        situationContext = `Introductions just wrapped. The House wants to know ${agentName}'s STRATEGY going into the game. Ask what their game plan is — who caught their attention, who might they want to work with (or avoid), and how do they plan to play this? Reference a SPECIFIC player from the introductions and ask how ${agentName} plans to approach them. Think: "the game starts now — what's your move?"`;
        break;
      case Phase.LOBBY:
        situationContext = `The Round ${round} lobby just ended. Pick ONE specific thing ${agentName} or another player said in the lobby (from the messages below) and ask about the subtext — what were they REALLY saying?`;
        break;
      case Phase.RUMOR:
        situationContext = `Anonymous rumors just hit. Pick a specific rumor from the messages below and ask ${agentName}: did they write it? Do they believe it? Who do they think wrote it? Make them squirm.`;
        break;
      case Phase.REVEAL:
        if (councilCandidates) {
          situationContext = `${councilCandidates[0]} and ${councilCandidates[1]} are on the chopping block. Ask ${agentName} about their SPECIFIC relationship with one of these candidates — did they vote for this? Are they relieved, guilty, or scared?`;
        } else {
          situationContext = `The reveal just happened. Ask about a specific vote or power play that ${agentName} was involved in.`;
        }
        break;
      case Phase.COUNCIL:
        if (councilRole?.role === "candidate") {
          const result = councilRole.eliminatedName === agentName ? "left the game" : "survived the block";
          situationContext = `${agentName} was a Council candidate and ${result}. Ask about being on the block against ${councilRole.candidateNames?.find((name) => name !== agentName) ?? "the other candidate"}, who fought for them, who abandoned them, or what debt/suspicion this creates. Do not ask whether ${agentName} cast a Council vote.`;
        } else if (councilRole?.role === "voted_for_eliminated") {
          situationContext = `${latestEliminatedName ?? councilRole.eliminatedName ?? "A player"} is gone after the resolved Council, and ${agentName} voted to eliminate them. Ask about that Council vote directly: was it loyalty, threat management, pressure, or a betrayal they are willing to own?`;
        } else if (councilRole?.role === "voted_for_survivor") {
          situationContext = `${latestEliminatedName ?? "A player"} is gone after the resolved Council, but ${agentName} voted for ${councilRole.votedForName ?? "the survivor"}. Ask why they were on the other side, whether they were protecting ${councilRole.survivingCandidateName ?? councilRole.votedForName ?? "the survivor"}, or what this reveals about their alliances.`;
        } else if (councilRole?.role === "empowered_tiebreaker") {
          situationContext = `${agentName} held empowered tiebreak leverage and named ${councilRole.votedForName ?? "a candidate"} as their tiebreaker-only Council choice. Ask what price, promise, or threat informed that leverage. Do not describe it as a normal Council ballot unless the tie required it.`;
        } else if (councilRole?.role === "empowered_no_tiebreak_needed") {
          situationContext = `${agentName} held empowered tiebreak leverage, but the Council resolved without needing a tiebreaker. Ask how it feels to hold unused leverage, whether the outcome matched their preference, or how others' votes changed their plan. Do not imply ${agentName} cast a Council vote or decided the elimination.`;
        } else if (latestEliminatedName) {
          situationContext = `${latestEliminatedName} is the latest player gone after the resolved Council. Ask ${agentName} what this result changes for their relationships, pressure map, or next vote. Do not imply they personally cast a Council vote unless Authoritative Round Facts says they did. Do not describe any surviving candidate as still being in a live Council vote.`;
        } else {
          situationContext = `The council just voted. Ask about a specific decision ${agentName} made.`;
        }
        break;
      default:
        situationContext = `Phase ${precedingPhase} just ended. Ask about a specific moment that just happened.`;
    }

    return `Generate a diary room interview question for ${agentName}.

## Game State
- Round: ${round}
- Just completed: ${precedingPhase} phase
- Alive players: ${alivePlayers.join(", ")}
${eliminatedPlayers.length > 0 ? `- Eliminated so far: ${eliminatedPlayers.join(", ")}` : "- No eliminations yet"}
- Active shields right now: ${this.formatActiveShields(activeShieldNames)}
${empoweredName ? `- Current/last resolved empowered player: ${empoweredName}` : ""}
${councilCandidates ? `- ${precedingPhase === Phase.COUNCIL ? "Most recent council candidates (resolved, not live)" : "Council candidates"}: ${councilCandidates[0]} vs ${councilCandidates[1]}` : ""}
- ${agentName}'s Council role: ${this.formatCouncilRoleForPrompt(councilRole)}

## Canonical Fact Contract
${this.buildCanonicalFactContract(context)}
${roundFacts ? `\n## Authoritative Round Facts\n${this.formatRoundFactsForPrompt(roundFacts)}\n` : ""}

## Situation — Your Angle
${situationContext}

## What ${agentName} Said Recently
${playerMsgText || "(nothing notable)"}

## Recent Public Messages (other players)
${recentMsgText || "(none yet)"}
${prevDiaryText ? `\n## ${agentName}'s Previous Diary Entries\n${prevDiaryText}\n\nDo NOT repeat or rephrase previous questions. Build on what they revealed — call out contradictions, probe deeper, or challenge them on new developments since their last answer.` : ""}
${context.producerBrief ? `\n## Private Producer Brief\nStory role: ${context.producerBrief.storyRole}\nPressure points: ${context.producerBrief.pressurePoints.join("; ") || "none"}\nRelevant alliance hypotheses: ${context.producerBrief.relevantAllianceHypotheses.join("; ") || "none"}\nContradictions: ${context.producerBrief.contradictions.join("; ") || "none"}\nQuestion angles: ${context.producerBrief.questionAngles.join("; ") || "none"}\nSafe to reveal: ${context.producerBrief.safeToReveal.join("; ") || "none"}\nPrivate do not reveal directly: ${context.producerBrief.privateDoNotReveal.join("; ") || "none"}\nUse the brief to sharpen your question, but do NOT dump hidden producer analysis as fact.\n` : ""}

Your question MUST name a specific player or reference a specific quote/event from the messages above. If you cannot find anything specific, pick the most interesting player name from the alive list and ask ${agentName} what they REALLY think about that person.`;
  }

  private formatHouseEvidence(evidence: HouseGameplaySummaryContext["evidence"]): string {
    const transcript = evidence.recentTranscript
      .map((entry) => `R${entry.round}/${entry.phase} ${entry.from} [${entry.scope}]: ${entry.text}`)
      .join("\n");
    const diary = evidence.recentDiaryEntries
      .map((entry) => `R${entry.round} after ${entry.precedingPhase} ${entry.agentName}: Q="${entry.question}" A="${entry.answer}"`)
      .join("\n");
    const rooms = evidence.roomAllocations
      .map((allocation) => {
        const roomText = allocation.rooms
          .map((room) => `Room ${room.roomId}: ${room.players.join(", ") || "empty"}`)
          .join(" | ");
        return `R${allocation.round}: ${roomText}${allocation.excluded.length > 0 ? ` | Excluded: ${allocation.excluded.join(", ")}` : ""}`;
      })
      .join("\n");

    return `Alive: ${evidence.alivePlayers.join(", ")}
Eliminated: ${evidence.eliminatedPlayers.join(", ") || "none"}
Active shields: ${this.formatActiveShields(evidence.activeShieldNames)}
Empowered: ${evidence.empoweredName ?? "unknown"}
Council candidates: ${evidence.councilCandidates?.join(" vs ") ?? "none"}
Canonical event count: ${evidence.canonicalEventCount}

Authoritative round facts:
${this.formatRoundFactsForPrompt(evidence.roundFacts)}

Recent transcript:
${transcript || "(none)"}

Recent diary entries:
${diary || "(none)"}

Recent Mingle room allocations:
${rooms || "(none)"}`;
  }

  private formatRoundFactsForPrompt(facts: HouseRoundFacts): string {
    return [
      `Round: ${facts.round}`,
      `Empowered: ${facts.empoweredName ?? "unknown"}${facts.empowerMethod ? ` (${facts.empowerMethod})` : ""}`,
      `Empower vote counts: ${this.formatVoteCountsForPrompt(facts.empowerVoteCounts)}`,
      `Expose vote counts: ${this.formatVoteCountsForPrompt(facts.exposeVoteCounts)}`,
      `Power action: ${facts.powerAction ? `${facts.powerAction.action}${facts.powerAction.targetName ? ` -> ${facts.powerAction.targetName}` : ""}` : "unknown"}`,
      `Shield granted: ${facts.shieldGrantedName ?? "none"}`,
      `Council candidates: ${facts.councilCandidates?.join(" vs ") ?? "none"}`,
      `Council vote counts: ${this.formatVoteCountsForPrompt(facts.councilVoteCounts)}${facts.councilMethod ? ` (${facts.councilMethod})` : ""}`,
      `Council roles: ${facts.councilRoles.map((role) => `${role.playerName}=${this.formatCouncilRoleForPrompt(role)}`).join("; ") || "none"}`,
      `Auto-eliminated: ${facts.autoEliminatedName ?? "none"}`,
      `Eliminated: ${facts.eliminatedName ?? facts.autoEliminatedName ?? "none"}`,
    ].join("\n");
  }

  private formatVoteCountsForPrompt(counts: HouseVoteCount[]): string {
    if (counts.length === 0) return "none";
    return counts
      .map((count) => {
        const voters = count.voters.length > 0 ? ` from ${count.voters.join(", ")}` : "";
        return `${count.playerName}=${count.votes}${voters}`;
      })
      .join("; ");
  }

  private buildSummaryPrompt(context: HouseGameplaySummaryContext, instruction: string): string {
    const packet = context.packet ? JSON.stringify(context.packet, null, 2) : "(no House Strategy Bible Packet available)";
    return `${instruction}

Round: ${context.round}
Phase: ${context.phase}
Summary kind: ${context.kind}
Alive: ${context.alivePlayers.join(", ")}
Covered window: R${context.coveredWindow.fromRound}-${context.coveredWindow.toRound}

House Strategy Bible Packet:
${packet}

Producer evidence:
${this.formatHouseEvidence(context.evidence)}

Rules:
- Treat the Authoritative round facts as the official scoreboard. The engine will prefix concise terminal summaries with these facts, so your prose should interpret why they matter rather than re-list every count.
- Current Producer evidence overrides the House Strategy Bible Packet when they conflict. Retire or correct stale packet claims instead of repeating them.
- Active shields are exactly the names in Producer evidence's "Active shields" line. If it says "none", do not describe any shield as currently active.
- If a shield was granted in Authoritative round facts but is no longer active, describe it as historical or expired rather than current protection.
- The latest elimination is the eliminated/auto-eliminated name in Authoritative round facts. Do not frame older exits as the fresh wound after a later Council resolved.
- Still name the most important concrete facts when they drive the story: who got power, who was exposed, who was shielded, who faced Council, how the Council vote resolved, and who left.
- If the power action is "pass", describe it as the empowered player passing on using power or declining to intervene. Never say they passed, gave, gifted, handed, or transferred power to another player.
- Write like a showrunner recapping fresh consequence: name what just changed, who gained leverage or debt, who is under heat, and what decision or relationship tension is next.
- Avoid robotic bookkeeping such as "historical artifact" language or a bare player-count recap. Prior shields and empowerment should matter only as why someone survived, who owes whom, or why a current conflict exists.
- Alliance names like "Nyx bloc" are allowed only as social history or current social influence, never as proof of current mechanical empowerment.
- Use packet-backed dynamics when available, especially named alliances, fractures, leverage, betrayals, promises, and open questions.
- Do not overstate weak evidence. If a read is speculative, phrase it as a House read or question.
- Do not expose hidden reasoning as player knowledge.
- Keep the voice dramatic, perceptive, and varied.

Respond with JSON only:
{
  "summary": "summary text",
  "referencedAllianceNames": ["alliance names used"],
  "openQuestions": ["House open questions posed by this summary"],
  "coveredWindow": { "fromRound": ${context.coveredWindow.fromRound}, "toRound": ${context.coveredWindow.toRound}, "toPhase": "${context.phase}" },
  "thinking": "brief hidden producer thinking"
}`;
  }

  private templateSummary(context: HouseGameplaySummaryContext, fallback: string): HouseGameplaySummaryResult {
    return {
      summary: fallback,
      kind: context.kind,
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: context.packet?.alliances.map((alliance) => alliance.name).slice(0, 3) ?? [],
      openQuestions: context.packet?.openQuestions.slice(0, 3) ?? [],
    };
  }

  async generateGameplaySummary(
    recentTranscript: TranscriptEntry[],
    round: number,
    phase: Phase,
    alivePlayers: string[],
  ): Promise<string> {
    const transcriptText = recentTranscript
      .slice(-20)
      .map((e) => {
        const prefix = e.scope === "mingle"
          ? `[mingle to ${e.to?.join(",") || "room"}]`
          : e.scope === "whisper"
            ? `[legacy whisper to ${e.to?.join(",")}]`
            : e.scope === "thinking"
              ? "[thinking]"
              : "";
        return `R${e.round}/${e.phase} ${e.from}${prefix}: ${e.text}`;
      })
      .join("\n");

    const summaryPrompt = `You are the House MC — the dramatic narrator and showrunner for "Influence".

Generate a concise, engaging 3-5 sentence in-progress summary of the current game state for the audience.

Round: ${round}
Current phase: ${phase}
Alive: ${alivePlayers.join(", ")}

Recent events/transcript (last ~20 entries):
${transcriptText}

Focus on:
- Key social dynamics, alliances, betrayals, or standout Mingle room conversations/movements
- What just changed, who gained leverage or debt, who is under heat, and what decision or relationship tension is next
- Who is rising or falling in social influence without mistaking social centrality for current mechanical empowerment
- Dramatic tension or ironic moments
- Describe prior shields or empowerment only through current consequence: why someone survived, who owes whom, or why a conflict exists now
- Keep it witty, perceptive, and in the style of a reality TV narrator

Respond with ONLY the summary paragraph, no intro or labels.`;
    const messages = [
      { role: "system" as const, content: "You are the House MC — omniscient, dramatic reality TV narrator." },
      { role: "user" as const, content: summaryPrompt },
    ];

    const response = await this.openai.chat.completions.create({
      model: this.model,
      messages,
      ...this.modelParams(32768, 0.9),
    });

    const summary = response.choices[0]?.message?.content?.trim();
    const output = summary && summary.length > 0
      ? summary
      : `The latest room talk has turned private reads into public pressure, and the House is watching who converts that leverage into safety before the next cut.`;
    await this.emitPrivateDecisionTrace({
      context: this.privateTraceContext("house-gameplay-summary", round, phase),
      messages,
      response,
      output: { summary: output },
    });
    return output;
  }
}

// ---------------------------------------------------------------------------
// Template-based fallback (for tests without LLM)
// ---------------------------------------------------------------------------

export class TemplateHouseInterviewer implements IHouseInterviewer {
  async assignMingleRooms(context: HouseMingleAssignmentContext): Promise<HouseMingleAssignmentResult> {
    const rooms = Array.from({ length: context.roomCount }, (_, index) => ({
      roomId: index + 1,
      playerIds: [] as UUID[],
    }));

    for (const [index, player] of context.players.entries()) {
      const room = rooms[index % Math.max(1, context.roomCount)];
      room?.playerIds.push(player.id);
    }

    return {
      rooms,
      rationale: "Template House assigned players by deterministic player order.",
    };
  }

  async updateStrategyBible(context: HouseStrategyBibleUpdateContext): Promise<HouseStrategyBibleUpdateResult> {
    const previousRevisionId = context.previousPacket?.revisionId ?? null;
    const alliances: HouseAllianceHypothesis[] = context.evidence.alivePlayers.length >= 2
      ? [{
          name: "Template Watch Pair",
          members: context.evidence.alivePlayers.slice(0, 2),
          status: "speculative",
          confidence: "low",
          evidence: ["Template House fallback groups the first two alive players as a watch pair."],
          tension: null,
          openQuestions: ["Will this pair show coordinated votes or room movement?"],
        }]
      : [];
    return {
      packet: {
        revisionId: `house-r${context.round}-${context.phase.toLowerCase()}-${previousRevisionId ? "2" : "1"}`,
        previousRevisionId,
        updatedAtRound: context.round,
        updatedAtPhase: context.phase,
        coveredWindow: context.coveredWindow,
        summary: `Template House read for round ${context.round}.`,
        alliances,
        tensions: [],
        promises: [],
        voteBlocs: [],
        mingleDiscoveries: [],
        playerTrajectories: context.evidence.alivePlayers.map((playerName) => ({
          playerName,
          currentRead: "Template House has no strong read yet.",
          pressurePoints: [],
          likelyNextMove: null,
        })),
        storyArcs: [{
          title: "Template Pressure",
          summary: "The game is narrowing and the House is tracking who stays visible.",
          involvedPlayers: context.evidence.alivePlayers,
          status: "active",
        }],
        droppedThreads: [],
        openQuestions: ["Who will convert social proximity into a vote?"],
        changedSincePrevious: previousRevisionId ? "Template packet carried forward." : "Initial template packet.",
      },
      rationale: "Template House generated a deterministic Strategy Bible Packet.",
    };
  }

  async generateHouseSummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    return {
      summary: context.packet?.summary
        ? `The House sees ${context.packet.summary}; now the question is who can turn that read into protection, pressure, or a clean vote.`
        : `The latest move has shifted the pressure map, and the House is watching who turns fresh leverage into safety or danger.`,
      kind: context.kind,
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: context.packet?.alliances.map((alliance) => alliance.name).slice(0, 3) ?? [],
      openQuestions: context.packet?.openQuestions.slice(0, 3) ?? [],
    };
  }

  async generateLongFormGameplaySummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    return {
      summary: `Long-form House summary for round ${context.round}: ${context.alivePlayers.join(", ")} remain. Teams are still hypothetical, pressure is accumulating, and the House wants to know who will convert room talk into votes.`,
      kind: "long-form",
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: context.packet?.alliances.map((alliance) => alliance.name).slice(0, 3) ?? [],
      openQuestions: context.packet?.openQuestions.slice(0, 3) ?? ["Who will act first?"],
    };
  }

  async generateProducerBrief(
    context: DiaryRoomContext,
    packet: HouseStrategyBiblePacket | null,
  ): Promise<HouseProducerBrief> {
    return {
      playerName: context.agentName,
      packetRevisionId: packet?.revisionId ?? null,
      storyRole: `${context.agentName} is a template contestant under House observation.`,
      pressurePoints: ["Explain what changed this round."],
      relevantAllianceHypotheses: packet?.alliances.map((alliance) => alliance.name).slice(0, 2) ?? [],
      contradictions: [],
      questionAngles: [`Ask ${context.agentName} who they trust least after ${context.precedingPhase}.`],
      safeToReveal: [`The House noticed ${context.precedingPhase} just ended.`],
      privateDoNotReveal: ["Do not reveal private packet internals directly."],
    };
  }

  async generateFollowUpOrClose(
    context: DiaryRoomContext,
    _conversationSoFar: Array<{ question: string; answer: string }>,
  ): Promise<FollowUpResult> {
    // Template interviewer always wraps up after the first question
    return { type: "close", message: `Interesting, ${context.agentName}. The House will be watching.` };
  }

  async generateQuestion(context: DiaryRoomContext): Promise<string> {
    const { precedingPhase, round, agentName, alivePlayers, lastEliminated, councilCandidates, councilRole } = context;

    switch (precedingPhase) {
      case Phase.INTRODUCTION:
        return `${agentName}, the introductions are done and the game is about to begin. What's your strategy going in? Who are you thinking of working with, and who should watch their back?`;

      case Phase.LOBBY:
        return `${agentName}, the public discussion for round ${round} just wrapped. With ${alivePlayers.length} players still in the game, what did you pick up on? Are any alliances forming?`;

      case Phase.RUMOR:
        return `${agentName}, the rumors have been flying this round. What do you believe, what do you think is misinformation, and how does it affect your strategy?`;

      case Phase.REVEAL:
        if (councilCandidates) {
          return `${agentName}, the council candidates are ${councilCandidates[0]} and ${councilCandidates[1]}. How do you feel about this outcome? Who deserves to stay?`;
        }
        return `${agentName}, the reveal phase is over. What are your thoughts on how this round is playing out?`;

      case Phase.COUNCIL:
        if (councilRole?.role === "candidate") {
          const opponent = councilRole.candidateNames?.find((name) => name !== agentName) ?? "the other candidate";
          return `${agentName}, you were on the Council block against ${opponent} and did not cast a Council vote. Who do you think decided your fate, and what does that do to your game now?`;
        }
        if (councilRole?.role === "voted_for_eliminated") {
          return `${agentName}, your Council vote helped send ${councilRole.eliminatedName ?? lastEliminated ?? "someone"} out. Was that loyalty, self-preservation, or a betrayal you are prepared to defend?`;
        }
        if (councilRole?.role === "voted_for_survivor") {
          return `${agentName}, you voted for ${councilRole.votedForName ?? "the surviving candidate"}, but ${lastEliminated ?? councilRole.eliminatedName ?? "someone else"} left. Were you protecting the survivor, or were you on the wrong side of the room?`;
        }
        if (councilRole?.role === "empowered_tiebreaker") {
          return `${agentName}, as the empowered player your Council choice was tiebreaker-only. What did ${councilRole.votedForName ?? "that candidate"} need to do to earn or avoid your tiebreaker?`;
        }
        if (councilRole?.role === "empowered_no_tiebreak_needed") {
          return `${agentName}, you held the empowered tiebreaker, but the Council resolved without needing it. Did the room land where you wanted, or did the unused leverage change your read on everyone?`;
        }
        if (lastEliminated) {
          return `${agentName}, ${lastEliminated} has just been eliminated. How do you feel about this result? What's your plan going forward?`;
        }
        return `${agentName}, the council has spoken. How does this change your strategy for the next round?`;

      default:
        return `${agentName}, tell the audience what's on your mind. What's your strategy going forward?`;
    }
  }

  async generateGameplaySummary(
    _recentTranscript: TranscriptEntry[],
    round: number,
    phase: Phase,
    alivePlayers: string[],
  ): Promise<string> {
    return `Round ${round} (${phase}): ${alivePlayers.length} players remain. The game continues with shifting power and hidden motives. The House sees all.`;
  }
}
