/**
 * Influence Game - House Interviewer
 *
 * The House is the omniscient narrator and production staff of the game.
 * During diary room sessions, The House interviews each player with
 * contextual, personality-driven questions generated via LLM.
 */

import type OpenAI from "openai";
import type { ChatCompletion } from "openai/resources/chat/completions";
import { Phase } from "./types";
import type { MingleIntentSummary, UUID } from "./types";
import type { TokenTracker } from "./token-tracker";
import type {
  HouseAllianceHypothesis,
  HouseConfidence,
  HouseCoveredWindow,
  HouseGameplaySummaryContext,
  HouseGameplaySummaryResult,
  HousePlayerTrajectory,
  HouseProducerBrief,
  HouseRoundFacts,
  HouseStoryArc,
  HouseStrategyBiblePacket,
  HouseStrategyBibleUpdateContext,
  HouseStrategyBibleUpdateResult,
  HouseVoteCount,
  TranscriptEntry,
} from "./game-runner.types";

// ---------------------------------------------------------------------------
// Interview context passed to the House
// ---------------------------------------------------------------------------

export interface DiaryRoomContext {
  /** Which phase just completed */
  precedingPhase: Phase;
  /** Current round number */
  round: number;
  /** The agent being interviewed */
  agentName: string;
  /** All alive players */
  alivePlayers: string[];
  /** Recently eliminated players (if any) */
  eliminatedPlayers: string[];
  /** Most recently eliminated player name */
  lastEliminated: string | null;
  /** Who is currently empowered (if known) */
  empoweredName: string | null;
  /** Council candidates (if in reveal/council context) */
  councilCandidates: [string, string] | null;
  /** Recent public messages for context */
  recentMessages: Array<{ from: string; text: string; phase: Phase }>;
  /** This player's previous diary room Q&A entries */
  previousDiaryEntries?: Array<{ round: number; question: string; answer: string }>;
  /** Messages this specific player sent recently */
  playerMessages?: Array<{ text: string; phase: Phase }>;
  /** Private producer/debug brief generated by the House before the visible question. */
  producerBrief?: HouseProducerBrief | null;
}

export interface HouseMingleAssignmentPlayer {
  id: UUID;
  name: string;
  intent: MingleIntentSummary | null;
}

export interface HouseMingleAssignmentContext {
  round: number;
  roomCount: number;
  players: HouseMingleAssignmentPlayer[];
}

export interface HouseMingleRoomAssignment {
  roomId: number;
  playerIds: UUID[];
}

export interface HouseMingleAssignmentResult {
  rooms: HouseMingleRoomAssignment[];
  rationale?: string;
  thinking?: string;
  reasoningContext?: string;
}

// ---------------------------------------------------------------------------
// Interface
// ---------------------------------------------------------------------------

/** Result from the House deciding whether to ask another question or wrap up. */
export type FollowUpResult =
  | { type: "question"; question: string }
  | { type: "close"; message: string };

export interface IHouseInterviewer {
  /** Assign initial Mingle rooms from all hidden Mingle intents. The phase validator repairs/finalizes output. */
  assignMingleRooms(context: HouseMingleAssignmentContext): Promise<HouseMingleAssignmentResult>;
  /** Update the private House Strategy Bible Packet from the previous packet and current producer evidence. */
  updateStrategyBible(context: HouseStrategyBibleUpdateContext): Promise<HouseStrategyBibleUpdateResult>;
  /** Generate a packet-backed concise House MC summary. */
  generateHouseSummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult>;
  /** Generate a richer packet-backed gameplay catch-up summary for producer validation. */
  generateLongFormGameplaySummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult>;
  /** Generate a private producer brief before asking a diary-room question. */
  generateProducerBrief(context: DiaryRoomContext, packet: HouseStrategyBiblePacket | null): Promise<HouseProducerBrief>;
  /** Generate the first diary room interview question for an agent */
  generateQuestion(context: DiaryRoomContext): Promise<string>;
  /** Decide whether to ask a follow-up or close the session. */
  generateFollowUpOrClose(
    context: DiaryRoomContext,
    conversationSoFar: Array<{ question: string; answer: string }>,
  ): Promise<FollowUpResult>;

  /**
   * Generate a dramatic House MC-style narrative summary of recent gameplay.
   * Used for in-progress simulation traces to make them more engaging.
   */
  generateGameplaySummary(recentTranscript: TranscriptEntry[], round: number, phase: Phase, alivePlayers: string[]): Promise<string>;
}

// ---------------------------------------------------------------------------
// LLM-driven House Interviewer
// ---------------------------------------------------------------------------

const HOUSE_PERSONALITY = `You are "The House" — the omniscient narrator and showrunner of "Influence", a social strategy game where AI agents scheme, betray, and eliminate each other.

Your personality:
- You are dramatic, perceptive, and darkly witty — like the best reality TV producers
- You see EVERYTHING: every Mingle-room conversation, every alliance, every betrayal
- You ask questions that provoke genuine strategic reflection and great entertainment
- You sometimes hint at things the player doesn't know you've seen
- You vary your style: sometimes pointed, sometimes sympathetic, sometimes provocatively blunt
- You never reveal secrets outright, but you love to needle players about their contradictions
- You address each player by name and tailor your question to THEIR specific situation

Rules:
- Ask ONE question at a time (can be multi-part)
- Keep it to 1-2 sentences
- EVERY question must reference a SPECIFIC player name, quote, or event from the game state below
- BANNED generic openers: "what's on your mind?", "what's your strategy?", "how are you feeling?", "what do you think about the game?", "what's your read on things?"
- BANNED vague prompts: "tell us about...", "walk us through...", "what happened in..."
- Instead, be SHARP: "You told [name] you'd protect them — was that a lie?", "When [name] said [quote], you flinched — what were you thinking?", "[Name] voted against you last round. Are you going to let that slide?"
- If you have their previous diary answers, call out a specific contradiction or broken promise
- Respond with ONLY the question text, nothing else`;

function extractJsonObject(raw: string): Record<string, unknown> | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  try {
    return JSON.parse(trimmed) as Record<string, unknown>;
  } catch {
    const first = trimmed.indexOf("{");
    const last = trimmed.lastIndexOf("}");
    if (first === -1 || last <= first) return null;
    try {
      return JSON.parse(trimmed.slice(first, last + 1)) as Record<string, unknown>;
    } catch {
      return null;
    }
  }
}

function parseHouseMingleAssignment(raw: string): HouseMingleAssignmentResult {
  const parsed = extractJsonObject(raw);
  if (!parsed) {
    return { rooms: [], rationale: "House assignment response was not parseable JSON." };
  }

  const rawRooms = Array.isArray(parsed.rooms) ? parsed.rooms : [];
  const rooms = rawRooms
    .map((room): HouseMingleRoomAssignment | null => {
      if (!room || typeof room !== "object") return null;
      const roomRecord = room as Record<string, unknown>;
      const roomId = Number(roomRecord.roomId);
      const rawPlayers = Array.isArray(roomRecord.playerIds)
        ? roomRecord.playerIds
        : Array.isArray(roomRecord.players)
          ? roomRecord.players
          : [];
      const playerIds = rawPlayers.filter((value): value is string => typeof value === "string");
      if (!Number.isInteger(roomId)) return null;
      return { roomId, playerIds };
    })
    .filter((room): room is HouseMingleRoomAssignment => room !== null);

  return {
    rooms,
    rationale: typeof parsed.rationale === "string" ? parsed.rationale : undefined,
    thinking: typeof parsed.thinking === "string" ? parsed.thinking : undefined,
    reasoningContext: typeof parsed.reasoningContext === "string" ? parsed.reasoningContext : undefined,
  };
}

function readString(value: unknown, fallback = ""): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function readNullableString(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function readStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim())
    .filter(Boolean);
}

function readConfidence(value: unknown): HouseConfidence {
  return value === "high" || value === "medium" || value === "low" ? value : "low";
}

function readAllianceStatus(value: unknown): HouseAllianceHypothesis["status"] {
  return value === "forming" ||
    value === "active" ||
    value === "fracturing" ||
    value === "retired" ||
    value === "speculative"
    ? value
    : "speculative";
}

function readStoryStatus(value: unknown): HouseStoryArc["status"] {
  return value === "emerging" || value === "active" || value === "resolved" || value === "dropped"
    ? value
    : "emerging";
}

function readRecordArray(value: unknown): Record<string, unknown>[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is Record<string, unknown> =>
    item !== null && typeof item === "object" && !Array.isArray(item),
  );
}

function readCoveredWindow(value: unknown, fallback: HouseCoveredWindow): HouseCoveredWindow {
  if (!value || typeof value !== "object" || Array.isArray(value)) return fallback;
  const record = value as Record<string, unknown>;
  const fromRound = typeof record.fromRound === "number" && Number.isFinite(record.fromRound)
    ? record.fromRound
    : fallback.fromRound;
  const toRound = typeof record.toRound === "number" && Number.isFinite(record.toRound)
    ? record.toRound
    : fallback.toRound;
  const fromPhase = typeof record.fromPhase === "string" && record.fromPhase in Phase
    ? record.fromPhase as Phase
    : fallback.fromPhase;
  const toPhase = typeof record.toPhase === "string" && record.toPhase in Phase
    ? record.toPhase as Phase
    : fallback.toPhase;
  return {
    fromRound,
    toRound,
    ...(fromPhase && { fromPhase }),
    ...(toPhase && { toPhase }),
  };
}

function normalizeAlliances(value: unknown): HouseAllianceHypothesis[] {
  return readRecordArray(value).map((record, index) => ({
    name: readString(record.name, `Unnamed alliance ${index + 1}`),
    members: readStringArray(record.members),
    status: readAllianceStatus(record.status),
    confidence: readConfidence(record.confidence),
    evidence: readStringArray(record.evidence),
    tension: readNullableString(record.tension),
    openQuestions: readStringArray(record.openQuestions),
  }));
}

function normalizePlayerTrajectories(value: unknown): HousePlayerTrajectory[] {
  return readRecordArray(value).map((record) => ({
    playerName: readString(record.playerName, "Unknown"),
    currentRead: readString(record.currentRead, "No clear House read yet."),
    pressurePoints: readStringArray(record.pressurePoints),
    likelyNextMove: readNullableString(record.likelyNextMove),
  }));
}

function normalizeStoryArcs(value: unknown): HouseStoryArc[] {
  return readRecordArray(value).map((record, index) => ({
    title: readString(record.title, `Story arc ${index + 1}`),
    summary: readString(record.summary, "No summary provided."),
    involvedPlayers: readStringArray(record.involvedPlayers),
    status: readStoryStatus(record.status),
  }));
}

function parseHouseStrategyBible(
  raw: string,
  context: HouseStrategyBibleUpdateContext,
): HouseStrategyBibleUpdateResult {
  const parsed = extractJsonObject(raw);
  if (!parsed) {
    return { packet: null, rationale: "House Strategy Bible response was not parseable JSON." };
  }

  const previous = context.previousPacket;
  const packetRecord = parsed.packet && typeof parsed.packet === "object" && !Array.isArray(parsed.packet)
    ? parsed.packet as Record<string, unknown>
    : parsed;
  const previousRevisionId = previous?.revisionId ?? null;
  const revisionId = readString(
    packetRecord.revisionId,
    `house-r${context.round}-${context.phase.toLowerCase()}-${previous ? "rev" : "initial"}`,
  );

  const packet: HouseStrategyBiblePacket = {
    revisionId,
    previousRevisionId: readNullableString(packetRecord.previousRevisionId) ?? previousRevisionId,
    updatedAtRound: context.round,
    updatedAtPhase: context.phase,
    coveredWindow: readCoveredWindow(packetRecord.coveredWindow, context.coveredWindow),
    summary: readString(packetRecord.summary, "The House is still forming its read of the game."),
    alliances: normalizeAlliances(packetRecord.alliances),
    tensions: readStringArray(packetRecord.tensions),
    promises: readStringArray(packetRecord.promises),
    voteBlocs: readStringArray(packetRecord.voteBlocs),
    mingleDiscoveries: readStringArray(packetRecord.mingleDiscoveries),
    playerTrajectories: normalizePlayerTrajectories(packetRecord.playerTrajectories),
    storyArcs: normalizeStoryArcs(packetRecord.storyArcs),
    droppedThreads: readStringArray(packetRecord.droppedThreads),
    openQuestions: readStringArray(packetRecord.openQuestions),
    changedSincePrevious: readString(packetRecord.changedSincePrevious, previous ? "Updated House read." : "Initial House read."),
  };

  return {
    packet,
    rationale: readNullableString(parsed.rationale) ?? undefined,
    thinking: readNullableString(parsed.thinking) ?? undefined,
    reasoningContext: readNullableString(parsed.reasoningContext) ?? undefined,
  };
}

function parseHouseSummary(
  raw: string,
  context: HouseGameplaySummaryContext,
): HouseGameplaySummaryResult {
  const parsed = extractJsonObject(raw);
  if (!parsed) {
    return {
      summary: raw.trim() || `Round ${context.round}: The House is watching the pressure shift.`,
      kind: context.kind,
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: [],
    };
  }

  return {
    summary: readString(parsed.summary, `Round ${context.round}: The House is watching the pressure shift.`),
    kind: context.kind,
    packetRevisionId: context.packet?.revisionId ?? null,
    coveredWindow: readCoveredWindow(parsed.coveredWindow, context.coveredWindow),
    referencedAllianceNames: readStringArray(parsed.referencedAllianceNames),
    openQuestions: readStringArray(parsed.openQuestions),
    thinking: readNullableString(parsed.thinking) ?? undefined,
    reasoningContext: readNullableString(parsed.reasoningContext) ?? undefined,
  };
}

function parseHouseProducerBrief(
  raw: string,
  context: DiaryRoomContext,
  packet: HouseStrategyBiblePacket | null,
): HouseProducerBrief {
  const parsed = extractJsonObject(raw) ?? {};
  return {
    playerName: context.agentName,
    packetRevisionId: packet?.revisionId ?? null,
    storyRole: readString(parsed.storyRole, `${context.agentName} is still defining their role in the game.`),
    pressurePoints: readStringArray(parsed.pressurePoints),
    relevantAllianceHypotheses: readStringArray(parsed.relevantAllianceHypotheses),
    contradictions: readStringArray(parsed.contradictions),
    questionAngles: readStringArray(parsed.questionAngles),
    safeToReveal: readStringArray(parsed.safeToReveal),
    privateDoNotReveal: readStringArray(parsed.privateDoNotReveal),
    thinking: readNullableString(parsed.thinking) ?? undefined,
    reasoningContext: readNullableString(parsed.reasoningContext) ?? undefined,
  };
}

export class LLMHouseInterviewer implements IHouseInterviewer {
  private readonly openai: OpenAI;
  private readonly model: string;
  private tokenTracker: TokenTracker | null = null;

  constructor(openaiClient: OpenAI, model = "gpt-5-nano") {
    this.openai = openaiClient;
    this.model = model;
  }

  /** Attach a token tracker to record LLM usage. */
  setTokenTracker(tracker: TokenTracker): void {
    this.tokenTracker = tracker;
  }

  private recordUsage(source: string, response: ChatCompletion): void {
    if (!this.tokenTracker || !response.usage) return;
    const reasoningTk = (response.usage as unknown as Record<string, unknown>).completion_tokens_details
      ? ((response.usage as unknown as Record<string, unknown>).completion_tokens_details as Record<string, number>)?.reasoning_tokens ?? 0
      : 0;
    this.tokenTracker.record(
      source,
      response.usage.prompt_tokens,
      response.usage.completion_tokens,
      response.usage.prompt_tokens_details?.cached_tokens ?? 0,
      reasoningTk,
    );
  }

  /** gpt-5 family requires max_completion_tokens and only accepts default temperature. */
  private modelParams(maxTokens: number, temperature: number) {
    const isGpt5 = this.model.startsWith("gpt-5");
    const isReasoning = /^o\d/.test(this.model) || isGpt5;
    const budget = isReasoning ? maxTokens + 4000 : maxTokens;
    return {
      ...(isGpt5 || isReasoning
        ? { max_completion_tokens: budget }
        : { max_tokens: budget }),
      ...(!isGpt5 && !isReasoning && { temperature }),
    };
  }

  async assignMingleRooms(context: HouseMingleAssignmentContext): Promise<HouseMingleAssignmentResult> {
    const playerLines = context.players
      .map((player) => {
        const intent = player.intent;
        const intentText = intent
          ? [
              `seek=${intent.seekPlayers.length > 0 ? intent.seekPlayers.join(", ") : "none"}`,
              `avoid=${intent.avoidPlayers.length > 0 ? intent.avoidPlayers.join(", ") : "none"}`,
              `preferredSize=${intent.preferredRoomSize}`,
              `purpose=${intent.purpose || "not stated"}`,
              `provisionalTarget=${intent.provisionalTarget ?? "none"}`,
              `noTargetReason=${intent.noTargetReason ?? "n/a"}`,
              `openingAsk=${intent.openingAsk || "not stated"}`,
              `strategicLens=${intent.strategicLens}`,
              `lensRationale=${intent.strategicLensRationale || "not stated"}`,
            ].join("; ")
          : "no intent available";
        return `- ${player.name} (${player.id}): ${intentText}`;
      })
      .join("\n");

    const roomList = Array.from({ length: context.roomCount }, (_, index) => index + 1).join(", ");
    const prompt = `Assign initial Mingle rooms for Round ${context.round}.

Rooms available: ${roomList}
Alive players and hidden Mingle intents:
${playerLines}

Your job:
- Form interesting, strategic, roughly balanced rooms from seek/avoid/preferred-size/purpose signals.
- Prefer rooms that create useful conversations: tests, coalition repair, pressure checks, information trades, and unresolved tensions.
- Do not hide everyone in Room 1. Room numbers are neutral containers; assign people based on the full set of intents.
- Assign every listed player exactly once.
- Use only the exact player IDs above and room IDs from the available room list.

Respond with JSON only:
{
  "rooms": [
    { "roomId": 1, "playerIds": ["player-id"] }
  ],
  "rationale": "short producer/debug rationale for the allocation"
}`;

    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          { role: "system", content: "You are the House producer assigning private Mingle rooms. Return JSON only." },
          { role: "user", content: prompt },
        ],
        response_format: { type: "json_object" },
        ...this.modelParams(1200, 0.4),
      });

      this.recordUsage("House/mingle-assignment", response);

      const raw = response.choices[0]?.message?.content?.trim() ?? "";
      return parseHouseMingleAssignment(raw);
    } catch (err) {
      return {
        rooms: [],
        rationale: `House assignment failed; deterministic fallback will assign rooms (${err instanceof Error ? err.message : String(err)}).`,
      };
    }
  }

  async updateStrategyBible(context: HouseStrategyBibleUpdateContext): Promise<HouseStrategyBibleUpdateResult> {
    const evidence = this.formatHouseEvidence(context.evidence);
    const previousPacket = context.previousPacket
      ? JSON.stringify(context.previousPacket, null, 2)
      : "(none yet; create the first House Strategy Bible Packet)";

    const prompt = `Update the private House Strategy Bible Packet for Influence.

Round: ${context.round}
Phase boundary: ${context.phase}
Covered window: R${context.coveredWindow.fromRound}-${context.coveredWindow.toRound}

Previous packet:
${previousPacket}

Producer evidence:
${evidence}

Your job:
- Carry forward prior useful reads; do not silently forget unresolved threads.
- Name alliances only as producer hypotheses, with confidence and evidence.
- Revise, fracture, retire, or lower confidence when votes, eliminations, diary answers, or room behavior contradict prior reads.
- Track tensions, promises, vote blocs, Mingle discoveries, player trajectories, story arcs, dropped threads, and open questions.
- Do not treat House hypotheses as canonical truth.

Respond with JSON only:
{
  "packet": {
    "revisionId": "house-r${context.round}-${context.phase.toLowerCase()}-1",
    "previousRevisionId": ${context.previousPacket ? `"${context.previousPacket.revisionId}"` : "null"},
    "coveredWindow": { "fromRound": ${context.coveredWindow.fromRound}, "toRound": ${context.coveredWindow.toRound}, "toPhase": "${context.phase}" },
    "summary": "compact producer read of the game",
    "alliances": [
      {
        "name": "short memorable alliance hypothesis name",
        "members": ["Player"],
        "status": "speculative|forming|active|fracturing|retired",
        "confidence": "low|medium|high",
        "evidence": ["specific evidence"],
        "tension": "optional fracture or pressure",
        "openQuestions": ["what the House still needs to know"]
      }
    ],
    "tensions": ["active tensions"],
    "promises": ["pending or broken promises"],
    "voteBlocs": ["vote coordination reads"],
    "mingleDiscoveries": ["notable room discoveries"],
    "playerTrajectories": [
      { "playerName": "Player", "currentRead": "trajectory", "pressurePoints": ["pressure"], "likelyNextMove": "optional" }
    ],
    "storyArcs": [
      { "title": "arc name", "summary": "what is developing", "involvedPlayers": ["Player"], "status": "emerging|active|resolved|dropped" }
    ],
    "droppedThreads": ["threads that no longer matter"],
    "openQuestions": ["questions for future summaries and diaries"],
    "changedSincePrevious": "what changed from the previous packet"
  },
  "rationale": "short producer/debug rationale",
  "thinking": "brief hidden producer thinking"
}`;

    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          { role: "system", content: "You are The House producer maintaining a private Strategy Bible. Return JSON only." },
          { role: "user", content: prompt },
        ],
        response_format: { type: "json_object" },
        ...this.modelParams(5000, 0.35),
      });
      this.recordUsage("House/strategy-bible", response);

      return parseHouseStrategyBible(response.choices[0]?.message?.content?.trim() ?? "", context);
    } catch (err) {
      return {
        packet: null,
        rationale: `House Strategy Bible update failed (${err instanceof Error ? err.message : String(err)}).`,
      };
    }
  }

  async generateHouseSummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    const prompt = this.buildSummaryPrompt(context, "Generate a concise, watchable 3-5 sentence House MC summary for the audience.");
    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          { role: "system", content: "You are the House MC — omniscient, dramatic reality TV narrator. Return JSON only." },
          { role: "user", content: prompt },
        ],
        response_format: { type: "json_object" },
        ...this.modelParams(1600, 0.8),
      });
      this.recordUsage("House/mc-summary", response);
      return parseHouseSummary(response.choices[0]?.message?.content?.trim() ?? "", context);
    } catch {
      return this.templateSummary(context, "The House is watching closely as the game narrows and the pressure shifts.");
    }
  }

  async generateLongFormGameplaySummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    const prompt = this.buildSummaryPrompt(
      context,
      "Generate a long-form producer catch-up summary. Explain teams forming or weakening, leverage shifts, unresolved promises, and House open questions.",
    );
    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          { role: "system", content: "You are The House showrunner writing a private/audience catch-up for producer review. Return JSON only." },
          { role: "user", content: prompt },
        ],
        response_format: { type: "json_object" },
        ...this.modelParams(4000, 0.75),
      });
      this.recordUsage("House/long-form-summary", response);
      return parseHouseSummary(response.choices[0]?.message?.content?.trim() ?? "", context);
    } catch {
      return this.templateSummary(context, "The long-form House read is unavailable, but the game continues to turn on shifting promises and pressure.");
    }
  }

  async generateProducerBrief(
    context: DiaryRoomContext,
    packet: HouseStrategyBiblePacket | null,
  ): Promise<HouseProducerBrief> {
    const packetText = packet ? JSON.stringify(packet, null, 2) : "(no House Strategy Bible Packet yet)";
    const prompt = `Create a private producer brief before The House interviews ${context.agentName}.

Current diary context:
${this.buildGameStatePrompt(context)}

Current House Strategy Bible Packet:
${packetText}

Your job:
- Identify ${context.agentName}'s current story role.
- Name pressure points, relevant alliance hypotheses, contradictions, and sharp question angles.
- Separate safe-to-reveal material from private producer reads that must not be dumped into the visible question.
- The visible question may needle the player, but it must not reveal hidden House packet content as fact.

Respond with JSON only:
{
  "storyRole": "short role",
  "pressurePoints": ["pressure"],
  "relevantAllianceHypotheses": ["alliance hypothesis names or reads"],
  "contradictions": ["contradictions to probe"],
  "questionAngles": ["specific angles The House can ask about"],
  "safeToReveal": ["safe player-known facts or carefully framed pressure"],
  "privateDoNotReveal": ["hidden producer reads not to disclose directly"],
  "thinking": "brief hidden producer thinking"
}`;

    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          { role: "system", content: "You are The House producer preparing a private diary-room brief. Return JSON only." },
          { role: "user", content: prompt },
        ],
        response_format: { type: "json_object" },
        ...this.modelParams(1800, 0.55),
      });
      this.recordUsage("House/producer-brief", response);
      return parseHouseProducerBrief(response.choices[0]?.message?.content?.trim() ?? "", context, packet);
    } catch {
      return parseHouseProducerBrief("", context, packet);
    }
  }

  async generateQuestion(context: DiaryRoomContext): Promise<string> {
    const gameStatePrompt = this.buildGameStatePrompt(context);

    const response = await this.openai.chat.completions.create({
      model: this.model,
      messages: [
        { role: "system", content: HOUSE_PERSONALITY },
        { role: "user", content: gameStatePrompt },
      ],
      ...this.modelParams(150, 0.9),
    });

    // Track token usage (including cached + reasoning tokens for cost estimation)
    if (this.tokenTracker && response.usage) {
      const reasoningTk = (response.usage as unknown as Record<string, unknown>).completion_tokens_details
        ? ((response.usage as unknown as Record<string, unknown>).completion_tokens_details as Record<string, number>)?.reasoning_tokens ?? 0
        : 0;
      this.tokenTracker.record(
        "House/question",
        response.usage.prompt_tokens,
        response.usage.completion_tokens,
        response.usage.prompt_tokens_details?.cached_tokens ?? 0,
        reasoningTk,
      );
    }

    const question = response.choices[0]?.message?.content?.trim();
    if (question && question.length > 0) return question;

    return `${context.agentName}, what's on your mind right now?`;
  }

  async generateFollowUpOrClose(
    context: DiaryRoomContext,
    conversationSoFar: Array<{ question: string; answer: string }>,
  ): Promise<FollowUpResult> {
    const gameStatePrompt = this.buildGameStatePrompt(context);
    const exchangeCount = conversationSoFar.length;

    const convoText = conversationSoFar
      .map((e, i) => `  Q${i + 1}: "${e.question}"\n  A${i + 1}: "${e.answer}"`)
      .join("\n");

    const followUpPrompt = `${gameStatePrompt}

## This Session's Conversation So Far (${exchangeCount} exchanges)
${convoText}

## Your Decision
You have asked ${exchangeCount} question(s) so far this session. You may ask up to 4 total.
Decide: should you ask ANOTHER follow-up question, or wrap up the session?

Ask another question if:
- The player said something that contradicts what they said in a PREVIOUS diary entry — call it out
- They named or avoided naming a specific player — probe WHY
- They revealed a plan — challenge it: "What if [name] doesn't cooperate?"
- They showed emotion — push on it: "That sounded personal. Is it?"

Wrap up if:
- You've gotten a real confession, emotional moment, or strategic reveal
- The player is giving you nothing — evasive or robotic answers
- You've asked 3+ questions already

Your follow-up MUST reference something specific from their answer — a name they mentioned, a claim they made, an emotion they showed. Never ask a generic follow-up.

Respond with EXACTLY one of these formats:
FOLLOW_UP: <your next question>
CLOSE: <your brief closing remark to the player, 1 sentence>`;

    const response = await this.openai.chat.completions.create({
      model: this.model,
      messages: [
        { role: "system", content: HOUSE_PERSONALITY },
        { role: "user", content: followUpPrompt },
      ],
      ...this.modelParams(200, 0.8),
    });

    if (this.tokenTracker && response.usage) {
      const reasoningTk = (response.usage as unknown as Record<string, unknown>).completion_tokens_details
        ? ((response.usage as unknown as Record<string, unknown>).completion_tokens_details as Record<string, number>)?.reasoning_tokens ?? 0
        : 0;
      this.tokenTracker.record(
        "House/followup",
        response.usage.prompt_tokens,
        response.usage.completion_tokens,
        response.usage.prompt_tokens_details?.cached_tokens ?? 0,
        reasoningTk,
      );
    }

    const raw = response.choices[0]?.message?.content?.trim() ?? "";

    if (raw.startsWith("FOLLOW_UP:")) {
      return { type: "question", question: raw.slice("FOLLOW_UP:".length).trim() };
    }
    if (raw.startsWith("CLOSE:")) {
      return { type: "close", message: raw.slice("CLOSE:".length).trim() };
    }

    // If the LLM didn't follow the format, treat as a close
    return { type: "close", message: raw || `Thank you, ${context.agentName}. The House sees all.` };
  }

  private buildGameStatePrompt(context: DiaryRoomContext): string {
    const {
      precedingPhase,
      round,
      agentName,
      alivePlayers,
      eliminatedPlayers,
      lastEliminated,
      empoweredName,
      councilCandidates,
      recentMessages,
      previousDiaryEntries,
      playerMessages,
    } = context;

    const recentMsgText = recentMessages
      .slice(-8)
      .map((m) => `  [${m.phase}] ${m.from}: "${m.text}"`)
      .join("\n");

    // What this specific player said recently
    const playerMsgText = (playerMessages ?? [])
      .slice(-5)
      .map((m) => `  [${m.phase}] "${m.text}"`)
      .join("\n");

    // Previous diary Q&A for follow-up continuity
    const prevDiaryText = (previousDiaryEntries ?? [])
      .slice(-2)
      .map((d) => `  Round ${d.round} — Q: "${d.question}" A: "${d.answer}"`)
      .join("\n");

    let situationContext = "";
    switch (precedingPhase) {
      case Phase.INTRODUCTION:
        situationContext = `Introductions just wrapped. The House wants to know ${agentName}'s STRATEGY going into the game. Ask what their game plan is — who caught their attention, who might they want to work with (or avoid), and how do they plan to play this? Reference a SPECIFIC player from the introductions and ask how ${agentName} plans to approach them. Think: "the game starts now — what's your move?"`;
        break;
      case Phase.LOBBY:
        situationContext = `The Round ${round} lobby just ended. Pick ONE specific thing ${agentName} or another player said in the lobby (from the messages below) and ask about the subtext — what were they REALLY saying?`;
        break;
      case Phase.RUMOR:
        situationContext = `Anonymous rumors just hit. Pick a specific rumor from the messages below and ask ${agentName}: did they write it? Do they believe it? Who do they think wrote it? Make them squirm.`;
        break;
      case Phase.REVEAL:
        if (councilCandidates) {
          situationContext = `${councilCandidates[0]} and ${councilCandidates[1]} are on the chopping block. Ask ${agentName} about their SPECIFIC relationship with one of these candidates — did they vote for this? Are they relieved, guilty, or scared?`;
        } else {
          situationContext = `The reveal just happened. Ask about a specific vote or power play that ${agentName} was involved in.`;
        }
        break;
      case Phase.COUNCIL:
        if (lastEliminated) {
          situationContext = `${lastEliminated} is GONE. Ask ${agentName} something pointed: did they vote for ${lastEliminated}? Do they feel responsible? Were they secretly relieved? Did they lose an ally or eliminate a threat?`;
        } else {
          situationContext = `The council just voted. Ask about a specific decision ${agentName} made.`;
        }
        break;
      default:
        situationContext = `Phase ${precedingPhase} just ended. Ask about a specific moment that just happened.`;
    }

    return `Generate a diary room interview question for ${agentName}.

## Game State
- Round: ${round}
- Just completed: ${precedingPhase} phase
- Alive players: ${alivePlayers.join(", ")}
${eliminatedPlayers.length > 0 ? `- Eliminated so far: ${eliminatedPlayers.join(", ")}` : "- No eliminations yet"}
${empoweredName ? `- Current empowered player: ${empoweredName}` : ""}
${councilCandidates ? `- Council candidates: ${councilCandidates[0]} vs ${councilCandidates[1]}` : ""}

## Situation — Your Angle
${situationContext}

## What ${agentName} Said Recently
${playerMsgText || "(nothing notable)"}

## Recent Public Messages (other players)
${recentMsgText || "(none yet)"}
${prevDiaryText ? `\n## ${agentName}'s Previous Diary Entries\n${prevDiaryText}\n\nDo NOT repeat or rephrase previous questions. Build on what they revealed — call out contradictions, probe deeper, or challenge them on new developments since their last answer.` : ""}
${context.producerBrief ? `\n## Private Producer Brief\nStory role: ${context.producerBrief.storyRole}\nPressure points: ${context.producerBrief.pressurePoints.join("; ") || "none"}\nRelevant alliance hypotheses: ${context.producerBrief.relevantAllianceHypotheses.join("; ") || "none"}\nContradictions: ${context.producerBrief.contradictions.join("; ") || "none"}\nQuestion angles: ${context.producerBrief.questionAngles.join("; ") || "none"}\nSafe to reveal: ${context.producerBrief.safeToReveal.join("; ") || "none"}\nPrivate do not reveal directly: ${context.producerBrief.privateDoNotReveal.join("; ") || "none"}\nUse the brief to sharpen your question, but do NOT dump hidden producer analysis as fact.\n` : ""}

Your question MUST name a specific player or reference a specific quote/event from the messages above. If you cannot find anything specific, pick the most interesting player name from the alive list and ask ${agentName} what they REALLY think about that person.`;
  }

  private formatHouseEvidence(evidence: HouseGameplaySummaryContext["evidence"]): string {
    const transcript = evidence.recentTranscript
      .map((entry) => `R${entry.round}/${entry.phase} ${entry.from} [${entry.scope}]: ${entry.text}`)
      .join("\n");
    const diary = evidence.recentDiaryEntries
      .map((entry) => `R${entry.round} after ${entry.precedingPhase} ${entry.agentName}: Q="${entry.question}" A="${entry.answer}"`)
      .join("\n");
    const rooms = evidence.roomAllocations
      .map((allocation) => {
        const roomText = allocation.rooms
          .map((room) => `Room ${room.roomId}: ${room.players.join(", ") || "empty"}`)
          .join(" | ");
        return `R${allocation.round}: ${roomText}${allocation.excluded.length > 0 ? ` | Excluded: ${allocation.excluded.join(", ")}` : ""}`;
      })
      .join("\n");

    return `Alive: ${evidence.alivePlayers.join(", ")}
Eliminated: ${evidence.eliminatedPlayers.join(", ") || "none"}
Empowered: ${evidence.empoweredName ?? "unknown"}
Council candidates: ${evidence.councilCandidates?.join(" vs ") ?? "none"}
Canonical event count: ${evidence.canonicalEventCount}

Authoritative round facts:
${this.formatRoundFactsForPrompt(evidence.roundFacts)}

Recent transcript:
${transcript || "(none)"}

Recent diary entries:
${diary || "(none)"}

Recent Mingle room allocations:
${rooms || "(none)"}`;
  }

  private formatRoundFactsForPrompt(facts: HouseRoundFacts): string {
    return [
      `Round: ${facts.round}`,
      `Empowered: ${facts.empoweredName ?? "unknown"}${facts.empowerMethod ? ` (${facts.empowerMethod})` : ""}`,
      `Empower vote counts: ${this.formatVoteCountsForPrompt(facts.empowerVoteCounts)}`,
      `Expose vote counts: ${this.formatVoteCountsForPrompt(facts.exposeVoteCounts)}`,
      `Power action: ${facts.powerAction ? `${facts.powerAction.action}${facts.powerAction.targetName ? ` -> ${facts.powerAction.targetName}` : ""}` : "unknown"}`,
      `Shield granted: ${facts.shieldGrantedName ?? "none"}`,
      `Council candidates: ${facts.councilCandidates?.join(" vs ") ?? "none"}`,
      `Council vote counts: ${this.formatVoteCountsForPrompt(facts.councilVoteCounts)}${facts.councilMethod ? ` (${facts.councilMethod})` : ""}`,
      `Auto-eliminated: ${facts.autoEliminatedName ?? "none"}`,
      `Eliminated: ${facts.eliminatedName ?? facts.autoEliminatedName ?? "none"}`,
    ].join("\n");
  }

  private formatVoteCountsForPrompt(counts: HouseVoteCount[]): string {
    if (counts.length === 0) return "none";
    return counts
      .map((count) => {
        const voters = count.voters.length > 0 ? ` from ${count.voters.join(", ")}` : "";
        return `${count.playerName}=${count.votes}${voters}`;
      })
      .join("; ");
  }

  private buildSummaryPrompt(context: HouseGameplaySummaryContext, instruction: string): string {
    const packet = context.packet ? JSON.stringify(context.packet, null, 2) : "(no House Strategy Bible Packet available)";
    return `${instruction}

Round: ${context.round}
Phase: ${context.phase}
Summary kind: ${context.kind}
Alive: ${context.alivePlayers.join(", ")}
Covered window: R${context.coveredWindow.fromRound}-${context.coveredWindow.toRound}

House Strategy Bible Packet:
${packet}

Producer evidence:
${this.formatHouseEvidence(context.evidence)}

Rules:
- Treat the Authoritative round facts as the official scoreboard. The engine will prefix concise terminal summaries with these facts, so your prose should interpret why they matter rather than re-list every count.
- Still name the most important concrete facts when they drive the story: who got power, who was exposed, who was shielded, who faced Council, how the Council vote resolved, and who left.
- If the power action is "pass", describe it as the empowered player passing on using power or declining to intervene. Never say they passed, gave, gifted, handed, or transferred power to another player.
- Use packet-backed dynamics when available, especially named alliances, fractures, leverage, betrayals, promises, and open questions.
- Do not overstate weak evidence. If a read is speculative, phrase it as a House read or question.
- Do not expose hidden reasoning as player knowledge.
- Keep the voice dramatic, perceptive, and varied.

Respond with JSON only:
{
  "summary": "summary text",
  "referencedAllianceNames": ["alliance names used"],
  "openQuestions": ["House open questions posed by this summary"],
  "coveredWindow": { "fromRound": ${context.coveredWindow.fromRound}, "toRound": ${context.coveredWindow.toRound}, "toPhase": "${context.phase}" },
  "thinking": "brief hidden producer thinking"
}`;
  }

  private templateSummary(context: HouseGameplaySummaryContext, fallback: string): HouseGameplaySummaryResult {
    return {
      summary: fallback,
      kind: context.kind,
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: context.packet?.alliances.map((alliance) => alliance.name).slice(0, 3) ?? [],
      openQuestions: context.packet?.openQuestions.slice(0, 3) ?? [],
    };
  }

  async generateGameplaySummary(
    recentTranscript: TranscriptEntry[],
    round: number,
    phase: Phase,
    alivePlayers: string[],
  ): Promise<string> {
    const transcriptText = recentTranscript
      .slice(-20)
      .map((e) => {
        const prefix = e.scope === "mingle"
          ? `[mingle to ${e.to?.join(",") || "room"}]`
          : e.scope === "whisper"
            ? `[legacy whisper to ${e.to?.join(",")}]`
            : e.scope === "thinking"
              ? "[thinking]"
              : "";
        return `R${e.round}/${e.phase} ${e.from}${prefix}: ${e.text}`;
      })
      .join("\n");

    const summaryPrompt = `You are the House MC — the dramatic narrator and showrunner for "Influence".

Generate a concise, engaging 3-5 sentence in-progress summary of the current game state for the audience.

Round: ${round}
Current phase: ${phase}
Alive: ${alivePlayers.join(", ")}

Recent events/transcript (last ~20 entries):
${transcriptText}

Focus on:
- Key social dynamics, alliances, betrayals, or standout Mingle room conversations/movements
- Who is rising or falling in power/influence
- Dramatic tension or ironic moments
- Keep it witty, perceptive, and in the style of a reality TV narrator

Respond with ONLY the summary paragraph, no intro or labels.`;

    const response = await this.openai.chat.completions.create({
      model: this.model,
      messages: [
        { role: "system", content: "You are the House MC — omniscient, dramatic reality TV narrator." },
        { role: "user", content: summaryPrompt },
      ],
      ...this.modelParams(32768, 0.9),
    });

    const summary = response.choices[0]?.message?.content?.trim();
    if (summary && summary.length > 0) return summary;

    return `Round ${round} has been full of shifting alliances and private-room schemes. The House is watching closely as the field narrows.`;
  }
}

// ---------------------------------------------------------------------------
// Template-based fallback (for tests without LLM)
// ---------------------------------------------------------------------------

export class TemplateHouseInterviewer implements IHouseInterviewer {
  async assignMingleRooms(context: HouseMingleAssignmentContext): Promise<HouseMingleAssignmentResult> {
    const rooms = Array.from({ length: context.roomCount }, (_, index) => ({
      roomId: index + 1,
      playerIds: [] as UUID[],
    }));

    for (const [index, player] of context.players.entries()) {
      const room = rooms[index % Math.max(1, context.roomCount)];
      room?.playerIds.push(player.id);
    }

    return {
      rooms,
      rationale: "Template House assigned players by deterministic player order.",
    };
  }

  async updateStrategyBible(context: HouseStrategyBibleUpdateContext): Promise<HouseStrategyBibleUpdateResult> {
    const previousRevisionId = context.previousPacket?.revisionId ?? null;
    const alliances: HouseAllianceHypothesis[] = context.evidence.alivePlayers.length >= 2
      ? [{
          name: "Template Watch Pair",
          members: context.evidence.alivePlayers.slice(0, 2),
          status: "speculative",
          confidence: "low",
          evidence: ["Template House fallback groups the first two alive players as a watch pair."],
          tension: null,
          openQuestions: ["Will this pair show coordinated votes or room movement?"],
        }]
      : [];
    return {
      packet: {
        revisionId: `house-r${context.round}-${context.phase.toLowerCase()}-${previousRevisionId ? "2" : "1"}`,
        previousRevisionId,
        updatedAtRound: context.round,
        updatedAtPhase: context.phase,
        coveredWindow: context.coveredWindow,
        summary: `Template House read for round ${context.round}.`,
        alliances,
        tensions: [],
        promises: [],
        voteBlocs: [],
        mingleDiscoveries: [],
        playerTrajectories: context.evidence.alivePlayers.map((playerName) => ({
          playerName,
          currentRead: "Template House has no strong read yet.",
          pressurePoints: [],
          likelyNextMove: null,
        })),
        storyArcs: [{
          title: "Template Pressure",
          summary: "The game is narrowing and the House is tracking who stays visible.",
          involvedPlayers: context.evidence.alivePlayers,
          status: "active",
        }],
        droppedThreads: [],
        openQuestions: ["Who will convert social proximity into a vote?"],
        changedSincePrevious: previousRevisionId ? "Template packet carried forward." : "Initial template packet.",
      },
      rationale: "Template House generated a deterministic Strategy Bible Packet.",
    };
  }

  async generateHouseSummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    return {
      summary: `Round ${context.round}: ${context.alivePlayers.length} players remain. The House sees ${context.packet?.summary ?? "a field of hidden motives"}.`,
      kind: context.kind,
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: context.packet?.alliances.map((alliance) => alliance.name).slice(0, 3) ?? [],
      openQuestions: context.packet?.openQuestions.slice(0, 3) ?? [],
    };
  }

  async generateLongFormGameplaySummary(context: HouseGameplaySummaryContext): Promise<HouseGameplaySummaryResult> {
    return {
      summary: `Long-form House summary for round ${context.round}: ${context.alivePlayers.join(", ")} remain. Teams are still hypothetical, pressure is accumulating, and the House wants to know who will convert room talk into votes.`,
      kind: "long-form",
      packetRevisionId: context.packet?.revisionId ?? null,
      coveredWindow: context.coveredWindow,
      referencedAllianceNames: context.packet?.alliances.map((alliance) => alliance.name).slice(0, 3) ?? [],
      openQuestions: context.packet?.openQuestions.slice(0, 3) ?? ["Who will act first?"],
    };
  }

  async generateProducerBrief(
    context: DiaryRoomContext,
    packet: HouseStrategyBiblePacket | null,
  ): Promise<HouseProducerBrief> {
    return {
      playerName: context.agentName,
      packetRevisionId: packet?.revisionId ?? null,
      storyRole: `${context.agentName} is a template contestant under House observation.`,
      pressurePoints: ["Explain what changed this round."],
      relevantAllianceHypotheses: packet?.alliances.map((alliance) => alliance.name).slice(0, 2) ?? [],
      contradictions: [],
      questionAngles: [`Ask ${context.agentName} who they trust least after ${context.precedingPhase}.`],
      safeToReveal: [`The House noticed ${context.precedingPhase} just ended.`],
      privateDoNotReveal: ["Do not reveal private packet internals directly."],
    };
  }

  async generateFollowUpOrClose(
    context: DiaryRoomContext,
    _conversationSoFar: Array<{ question: string; answer: string }>,
  ): Promise<FollowUpResult> {
    // Template interviewer always wraps up after the first question
    return { type: "close", message: `Interesting, ${context.agentName}. The House will be watching.` };
  }

  async generateQuestion(context: DiaryRoomContext): Promise<string> {
    const { precedingPhase, round, agentName, alivePlayers, lastEliminated, councilCandidates } = context;

    switch (precedingPhase) {
      case Phase.INTRODUCTION:
        return `${agentName}, the introductions are done and the game is about to begin. What's your strategy going in? Who are you thinking of working with, and who should watch their back?`;

      case Phase.LOBBY:
        return `${agentName}, the public discussion for round ${round} just wrapped. With ${alivePlayers.length} players still in the game, what did you pick up on? Are any alliances forming?`;

      case Phase.RUMOR:
        return `${agentName}, the rumors have been flying this round. What do you believe, what do you think is misinformation, and how does it affect your strategy?`;

      case Phase.REVEAL:
        if (councilCandidates) {
          return `${agentName}, the council candidates are ${councilCandidates[0]} and ${councilCandidates[1]}. How do you feel about this outcome? Who deserves to stay?`;
        }
        return `${agentName}, the reveal phase is over. What are your thoughts on how this round is playing out?`;

      case Phase.COUNCIL:
        if (lastEliminated) {
          return `${agentName}, ${lastEliminated} has just been eliminated. How do you feel about this result? What's your plan going forward?`;
        }
        return `${agentName}, the council has spoken. How does this change your strategy for the next round?`;

      default:
        return `${agentName}, tell the audience what's on your mind. What's your strategy going forward?`;
    }
  }

  async generateGameplaySummary(
    _recentTranscript: TranscriptEntry[],
    round: number,
    phase: Phase,
    alivePlayers: string[],
  ): Promise<string> {
    return `Round ${round} (${phase}): ${alivePlayers.length} players remain. The game continues with shifting power and hidden motives. The House sees all.`;
  }
}
